// Chronik: datierte Einzelereignisse ("was geschah wann").
// y = Jahr (negativ = v. Chr.), t = Text, w = deutscher Wikipedia-Artikel (optional).
// Wird im Epochen-Panel chronologisch gefiltert angezeigt.

const CHRONICLE = [
  // ===== Frühe Hochkulturen =====
  { y: -3200, t: "Sumerer entwickeln in Uruk die Keilschrift – die Geschichte wird schriftlich.", w: "Keilschrift" },
  { y: -3100, t: "Einigung Ober- und Unterägyptens – Beginn der Pharaonenzeit.", w: "Altes Ägypten" },
  { y: -2600, t: "Blüte der Indus-Kultur: Planstädte Harappa und Mohenjo-daro.", w: "Indus-Kultur" },
  { y: -2560, t: "Cheops-Pyramide vollendet – 146 m hoch, 4000 Jahre lang höchstes Bauwerk der Welt.", w: "Cheops-Pyramide" },
  { y: -2334, t: "Sargon von Akkad schafft das erste Großreich der Geschichte.", w: "Sargon von Akkad" },
  { y: -2100, t: "Zikkurat von Ur; das Gilgamesch-Epos entsteht – die erste große Dichtung.", w: "Gilgamesch-Epos" },
  { y: -1792, t: "Hammurapi wird König von Babylon – sein Gesetzeskodex wird Weltberühmt.", w: "Codex Hammurapi" },
  { y: -1600, t: "Shang-Dynastie in China: Orakelknochen tragen die früheste chinesische Schrift.", w: "Shang-Dynastie" },
  { y: -1500, t: "In Indien entstehen die Veden – Grundlagentexte des Hinduismus.", w: "Veden" },
  { y: -1350, t: "Echnaton wagt das erste Experiment eines Ein-Gott-Glaubens (Aton).", w: "Echnaton" },
  { y: -1274, t: "Schlacht von Kadesch: Ägypten gegen Hethiter – danach der erste Friedensvertrag.", w: "Schlacht bei Kadesch" },
  { y: -1200, t: "Bronzezeit-Kollaps: Seevölker, Dürren – fast alle Reiche des Ostmittelmeers stürzen.", w: "Seevölker" },

  // ===== Eisenzeit =====
  { y: -1046, t: "Die Zhou stürzen die Shang – Idee des „Mandats des Himmels“.", w: "Zhou-Dynastie" },
  { y: -1000, t: "David macht Jerusalem zur Hauptstadt; Salomo baut den ersten Tempel.", w: "Jerusalemer Tempel" },
  { y: -814, t: "Phönizier gründen Karthago – bald reichste Handelsstadt des Westens.", w: "Karthago" },
  { y: -776, t: "Erste Olympische Spiele in Olympia.", w: "Olympische Spiele der Antike" },
  { y: -753, t: "Legendäre Gründung Roms durch Romulus.", w: "Gründung Roms" },
  { y: -722, t: "Assyrien zerstört das Nordreich Israel – die „zehn verlorenen Stämme“.", w: "Israel (Nordreich)" },
  { y: -671, t: "Assyrien erobert Ägypten – größte Ausdehnung der Militärmacht.", w: "Asarhaddon" },
  { y: -612, t: "Fall Ninives: Babylonier und Meder zerschlagen Assyrien.", w: "Ninive" },
  { y: -587, t: "Nebukadnezar II. zerstört Jerusalem – Babylonisches Exil der Juden.", w: "Babylonisches Exil" },
  { y: -563, t: "Geburt Siddhartha Gautamas, des späteren Buddha (traditionelles Datum).", w: "Siddhartha Gautama" },
  { y: -551, t: "Geburt des Konfuzius in Lu.", w: "Konfuzius" },

  // ===== Perser & Griechen =====
  { y: -550, t: "Kyros der Große stürzt die Meder – Beginn des Perserreichs.", w: "Kyros II." },
  { y: -539, t: "Kyros nimmt Babylon ein und lässt die Juden heimkehren.", w: "Babylon" },
  { y: -525, t: "Persien erobert Ägypten – das Reich reicht nun vom Nil bis zum Indus.", w: "Kambyses II." },
  { y: -509, t: "Rom vertreibt die Könige – Beginn der Republik.", w: "Römische Republik" },
  { y: -508, t: "Kleisthenes' Reformen in Athen – Geburt der Demokratie.", w: "Kleisthenes von Athen" },
  { y: -490, t: "Schlacht bei Marathon: Athen schlägt die erste persische Invasion zurück.", w: "Schlacht bei Marathon" },
  { y: -480, t: "Thermopylen und Salamis: Griechenland übersteht Xerxes' Großangriff.", w: "Schlacht von Salamis" },
  { y: -447, t: "Baubeginn des Parthenon unter Perikles.", w: "Parthenon" },
  { y: -431, t: "Peloponnesischer Krieg beginnt: Athen gegen Sparta (bis 404).", w: "Peloponnesischer Krieg" },
  { y: -399, t: "Athen verurteilt Sokrates zum Schierlingsbecher.", w: "Sokrates" },
  { y: -338, t: "Chaironeia: Philipp II. von Makedonien unterwirft Griechenland.", w: "Schlacht von Chaironeia" },
  { y: -334, t: "Alexander der Große beginnt den Persienfeldzug.", w: "Alexanderzug" },
  { y: -331, t: "Gaugamela: das Perserreich fällt an Alexander.", w: "Schlacht von Gaugamela" },
  { y: -323, t: "Alexander stirbt 32-jährig in Babylon – die Diadochen teilen das Reich.", w: "Alexander der Große" },

  // ===== Hellenismus & Rom =====
  { y: -300, t: "Euklid verfasst in Alexandria die „Elemente“ – Mathematik-Lehrbuch für 2000 Jahre.", w: "Euklid" },
  { y: -268, t: "Ashoka wird Kaiser Indiens – nach Kalinga wendet er sich dem Buddhismus zu.", w: "Ashoka" },
  { y: -264, t: "Erster Punischer Krieg beginnt: Rom gegen Karthago (bis 241).", w: "Erster Punischer Krieg" },
  { y: -221, t: "Qin Shihuangdi eint China – Große Mauer, Terrakotta-Armee, ein Reich.", w: "Qin Shihuangdi" },
  { y: -218, t: "Hannibal überquert mit Kriegselefanten die Alpen.", w: "Hannibal" },
  { y: -216, t: "Cannae: Hannibals Vernichtungssieg – Roms schwärzeste Stunde.", w: "Schlacht von Cannae" },
  { y: -202, t: "Zama: Scipio besiegt Hannibal – Rom beherrscht das Westmittelmeer.", w: "Schlacht von Zama" },
  { y: -146, t: "Rom zerstört Karthago und Korinth im selben Jahr.", w: "Dritter Punischer Krieg" },
  { y: -133, t: "Tiberius Gracchus' Landreform scheitert blutig – die Krise der Republik beginnt.", w: "Tiberius Sempronius Gracchus" },
  { y: -73, t: "Spartacus führt den größten Sklavenaufstand der Antike (bis 71).", w: "Spartacus" },
  { y: -58, t: "Caesar beginnt die Eroberung Galliens (bis 50).", w: "Gallischer Krieg" },
  { y: -49, t: "„Alea iacta est“ – Caesar überschreitet den Rubikon: Bürgerkrieg.", w: "Gaius Iulius Caesar" },
  { y: -44, t: "Iden des März: Caesar wird im Senat ermordet.", w: "Attentat auf Gaius Iulius Caesar" },
  { y: -31, t: "Actium: Octavian besiegt Antonius und Kleopatra.", w: "Schlacht bei Actium" },

  // ===== Kaiserzeit =====
  { y: -27, t: "Octavian wird „Augustus“ – Beginn der römischen Kaiserzeit.", w: "Augustus" },
  { y: 9, t: "Varusschlacht: Arminius vernichtet drei Legionen im Teutoburger Wald.", w: "Varusschlacht" },
  { y: 30, t: "Kreuzigung Jesu von Nazareth in Jerusalem (ca.).", w: "Jesus von Nazaret" },
  { y: 43, t: "Rom erobert Britannien unter Kaiser Claudius.", w: "Britannien (Provinz)" },
  { y: 64, t: "Rom brennt – Nero macht die Christen zu Sündenböcken.", w: "Großer Brand Roms" },
  { y: 70, t: "Titus zerstört Jerusalem und den Tempel – Beginn der jüdischen Diaspora.", w: "Jüdischer Krieg" },
  { y: 79, t: "Vesuvausbruch begräbt Pompeji und Herculaneum.", w: "Pompeji" },
  { y: 105, t: "Cai Lun perfektioniert in China das Papier.", w: "Papier" },
  { y: 117, t: "Unter Trajan erreicht Rom die größte Ausdehnung.", w: "Trajan" },
  { y: 122, t: "Baubeginn des Hadrianswalls in Britannien.", w: "Hadrianswall" },
  { y: 165, t: "Antoninische Pest: Seuche schwächt das Imperium (bis 180).", w: "Antoninische Pest" },

  // ===== Spätantike =====
  { y: 212, t: "Caracalla verleiht allen freien Reichsbewohnern das Bürgerrecht.", w: "Constitutio Antoniniana" },
  { y: 220, t: "Ende der Han-Dynastie – China zerfällt für 350 Jahre.", w: "Han-Dynastie" },
  { y: 235, t: "Reichskrise: 50 Jahre Soldatenkaiser, Invasionen, Inflation (bis 284).", w: "Reichskrise des 3. Jahrhunderts" },
  { y: 284, t: "Diokletian reorganisiert das Reich (Tetrarchie).", w: "Diokletian" },
  { y: 313, t: "Mailänder Vereinbarung: Konstantin erlaubt das Christentum.", w: "Mailänder Vereinbarung" },
  { y: 325, t: "Konzil von Nizäa: erstes ökumenisches Konzil, Glaubensbekenntnis.", w: "Erstes Konzil von Nicäa" },
  { y: 330, t: "Konstantinopel wird eingeweiht – das „neue Rom“.", w: "Konstantinopel" },
  { y: 375, t: "Hunneneinbruch löst die Völkerwanderung aus.", w: "Völkerwanderung" },
  { y: 378, t: "Adrianopel: Goten vernichten das Ostheer, Kaiser Valens fällt.", w: "Schlacht von Adrianopel (378)" },
  { y: 380, t: "Christentum wird römische Staatsreligion.", w: "Drei-Kaiser-Edikt" },
  { y: 395, t: "Endgültige Reichsteilung in Ost und West.", w: "Reichsteilung von 395" },
  { y: 410, t: "Alarichs Westgoten plündern Rom – Schock für die antike Welt.", w: "Plünderung Roms (410)" },
  { y: 451, t: "Katalaunische Felder: Attila wird gestoppt.", w: "Schlacht auf den Katalaunischen Feldern" },
  { y: 455, t: "Vandalen plündern Rom (daher „Vandalismus“).", w: "Vandalen" },
  { y: 476, t: "Odoaker setzt den letzten weströmischen Kaiser ab.", w: "Romulus Augustulus" },

  // ===== Frühmittelalter =====
  { y: 481, t: "Chlodwig wird Frankenkönig; um 496 katholische Taufe – Weichenstellung Europas.", w: "Chlodwig I." },
  { y: 529, t: "Benedikt gründet Montecassino; Justinian schließt Platons Akademie.", w: "Benedikt von Nursia" },
  { y: 537, t: "Hagia Sophia vollendet – größte Kirche der Welt für 1000 Jahre.", w: "Hagia Sophia" },
  { y: 541, t: "Justinianische Pest: erste dokumentierte Pandemie (Millionen Tote).", w: "Justinianische Pest" },
  { y: 568, t: "Langobarden erobern Norditalien.", w: "Langobarden" },
  { y: 589, t: "Sui-Dynastie eint China wieder; bald folgt der Kaiserkanal.", w: "Sui-Dynastie" },
  { y: 622, t: "Hidschra: Mohammed zieht nach Medina – Jahr 1 des islamischen Kalenders.", w: "Hidschra" },
  { y: 632, t: "Tod Mohammeds; die Kalifen beginnen die Expansion.", w: "Mohammed" },
  { y: 636, t: "Jarmuk und Kadesia: Araber besiegen Byzanz und Persien.", w: "Schlacht am Jarmuk" },
  { y: 661, t: "Ermordung Alis – Spaltung in Sunniten und Schiiten; Umayyaden übernehmen.", w: "Ali ibn Abi Talib" },
  { y: 698, t: "Karthago fällt an die Araber – Nordafrika wird islamisch.", w: "Islamische Expansion" },
  { y: 711, t: "Tariq überquert Gibraltar – das Westgotenreich Spanien fällt.", w: "Al-Andalus" },
  { y: 717, t: "Konstantinopel widersteht der großen arabischen Belagerung.", w: "Belagerung von Konstantinopel (717–718)" },
  { y: 726, t: "Byzantinischer Bilderstreit beginnt (bis 843).", w: "Byzantinischer Bilderstreit" },
  { y: 732, t: "Karl Martell stoppt die Araber bei Tours und Poitiers.", w: "Schlacht von Tours und Poitiers" },
  { y: 750, t: "Abbasiden stürzen die Umayyaden; ein Umayyade flieht nach Córdoba.", w: "Abbasiden-Kalifat" },

  // ===== Karolinger & Wikinger =====
  { y: 751, t: "Schlacht am Talas: Araber schlagen China – Papiermacher gelangen nach Westen. Pippin wird Frankenkönig.", w: "Schlacht am Talas" },
  { y: 762, t: "Gründung Bagdads durch Kalif al-Mansur.", w: "Bagdad" },
  { y: 793, t: "Wikinger überfallen Lindisfarne – Beginn der Wikingerzeit.", w: "Lindisfarne" },
  { y: 800, t: "Kaiserkrönung Karls des Großen in Rom.", w: "Karl der Große" },
  { y: 843, t: "Vertrag von Verdun teilt das Frankenreich – Keimzellen Frankreichs und Deutschlands.", w: "Vertrag von Verdun" },
  { y: 862, t: "Rurik in Nowgorod – Legendenbeginn der Rus.", w: "Rurik" },
  { y: 871, t: "Alfred der Große verteidigt Wessex gegen die Dänen.", w: "Alfred der Große" },
  { y: 911, t: "Wikinger Rollo erhält die Normandie als Lehen.", w: "Rollo (Normandie)" },
  { y: 929, t: "Abd ar-Rahman III. erklärt Córdoba zum Kalifat – Blüte von al-Andalus.", w: "Kalifat von Córdoba" },
  { y: 955, t: "Lechfeldschlacht: Otto I. besiegt die Ungarn.", w: "Schlacht auf dem Lechfeld" },
  { y: 962, t: "Kaiserkrönung Ottos I. – Beginn des Heiligen Römischen Reichs.", w: "Otto I. (HRR)" },
  { y: 987, t: "Hugo Capet wird König – die Kapetinger regieren Frankreich 800 Jahre.", w: "Hugo Capet" },
  { y: 988, t: "Taufe der Kiewer Rus – Osteuropa wird orthodox.", w: "Wladimir I." },
  { y: 1000, t: "Leif Eriksson erreicht Amerika („Vinland“); Ungarn wird christliches Königreich.", w: "Leif Eriksson" },

  // ===== Hochmittelalter =====
  { y: 1054, t: "Großes Schisma: Trennung von katholischer und orthodoxer Kirche.", w: "Morgenländisches Schisma" },
  { y: 1066, t: "Hastings: Wilhelm der Eroberer nimmt England.", w: "Schlacht bei Hastings" },
  { y: 1071, t: "Manzikert: Seldschuken schlagen Byzanz – Anatolien wird türkisch.", w: "Schlacht bei Manzikert" },
  { y: 1077, t: "Heinrich IV. im Büßerhemd vor Canossa.", w: "Gang nach Canossa" },
  { y: 1085, t: "Kastilien erobert Toledo – Übersetzerschulen bringen Aristoteles nach Europa.", w: "Toledo" },
  { y: 1088, t: "Bologna: die erste Universität Europas entsteht.", w: "Universität Bologna" },
  { y: 1095, t: "Papst Urban II. ruft in Clermont zum Kreuzzug.", w: "Erster Kreuzzug" },
  { y: 1099, t: "Kreuzfahrer erobern Jerusalem – mit furchtbarem Massaker.", w: "Belagerung von Jerusalem (1099)" },
  { y: 1122, t: "Wormser Konkordat beendet den Investiturstreit.", w: "Wormser Konkordat" },
  { y: 1152, t: "Friedrich Barbarossa wird König – Konflikt mit Papst und lombardischen Städten.", w: "Friedrich I. (HRR)" },
  { y: 1187, t: "Hattin: Saladin vernichtet das Kreuzfahrerheer und nimmt Jerusalem.", w: "Schlacht bei Hattin" },
  { y: 1189, t: "Dritter Kreuzzug: Barbarossa (ertrinkt 1190), Richard Löwenherz gegen Saladin.", w: "Dritter Kreuzzug" },

  // ===== Mongolensturm =====
  { y: 1204, t: "Vierter Kreuzzug plündert das christliche Konstantinopel.", w: "Vierter Kreuzzug" },
  { y: 1206, t: "Temüdschin wird Dschingis Khan – die Mongolen brechen auf.", w: "Dschingis Khan" },
  { y: 1212, t: "Las Navas de Tolosa: Wende der Reconquista.", w: "Schlacht bei Las Navas de Tolosa" },
  { y: 1215, t: "Magna Carta: der englische König wird ans Recht gebunden.", w: "Magna Carta" },
  { y: 1235, t: "Sundiata Keïta gründet das Malireich.", w: "Sundiata Keïta" },
  { y: 1241, t: "Mongolen siegen bei Liegnitz – und ziehen wegen Thronfolge ab.", w: "Schlacht bei Wahlstatt" },
  { y: 1258, t: "Mongolen zerstören Bagdad – Ende des Abbasiden-Kalifats.", w: "Eroberung von Bagdad (1258)" },
  { y: 1260, t: "Ain Dschalut: Mamluken fügen den Mongolen die erste echte Niederlage zu.", w: "Schlacht bei ʿAin Dschālūt" },
  { y: 1271, t: "Marco Polo bricht nach China auf; Kublai Khan gründet die Yuan-Dynastie.", w: "Marco Polo" },
  { y: 1274, t: "Thomas von Aquin stirbt; „Kamikaze“-Taifun rettet Japan vor den Mongolen.", w: "Thomas von Aquin" },
  { y: 1291, t: "Akkon fällt – Ende der Kreuzfahrerstaaten. Rütlischwur: Ursprung der Schweiz.", w: "Belagerung von Akkon (1291)" },

  // ===== Spätmittelalter =====
  { y: 1309, t: "Papsttum zieht nach Avignon („Babylonische Gefangenschaft“, bis 1377).", w: "Avignonesisches Papsttum" },
  { y: 1324, t: "Mansa Musas legendäre Pilgerfahrt – Malis Gold lässt Kairos Goldpreis abstürzen.", w: "Mansa Musa" },
  { y: 1337, t: "Hundertjähriger Krieg beginnt: England gegen Frankreich.", w: "Hundertjähriger Krieg" },
  { y: 1347, t: "Der Schwarze Tod erreicht Europa – ein Drittel der Bevölkerung stirbt.", w: "Schwarzer Tod" },
  { y: 1356, t: "Goldene Bulle regelt die Königswahl durch sieben Kurfürsten.", w: "Goldene Bulle" },
  { y: 1368, t: "Ming-Dynastie vertreibt die Mongolen aus China.", w: "Ming-Dynastie" },
  { y: 1378, t: "Abendländisches Schisma: zwei, später drei Päpste (bis 1417).", w: "Abendländisches Schisma" },
  { y: 1389, t: "Amselfeld: Osmanen brechen die serbische Macht.", w: "Schlacht auf dem Amselfeld" },
  { y: 1402, t: "Timur schlägt die Osmanen bei Ankara – Gnadenfrist für Byzanz.", w: "Schlacht bei Ankara" },
  { y: 1405, t: "Zheng Hes Riesenflotten stechen in See (bis 1433, bis Ostafrika).", w: "Zheng He" },
  { y: 1410, t: "Tannenberg: Polen-Litauen bricht die Macht des Deutschen Ordens.", w: "Schlacht bei Tannenberg (1410)" },
  { y: 1415, t: "Azincourt: englische Langbögen demütigen Frankreichs Ritter. Jan Hus verbrannt.", w: "Schlacht von Azincourt" },
  { y: 1429, t: "Jeanne d'Arc befreit Orléans – Wende des Kriegs.", w: "Jeanne d’Arc" },
  { y: 1450, t: "Gutenberg druckt mit beweglichen Lettern (ca.) – Medienrevolution.", w: "Johannes Gutenberg" },
  { y: 1453, t: "Konstantinopel fällt an Mehmed II.; der Hundertjährige Krieg endet.", w: "Eroberung von Konstantinopel (1453)" },

  // ===== Renaissance & Entdeckungen =====
  { y: 1455, t: "Rosenkriege in England beginnen (bis 1485: Tudors).", w: "Rosenkriege" },
  { y: 1469, t: "Heirat Isabellas und Ferdinands – Spanien entsteht.", w: "Katholische Könige" },
  { y: 1480, t: "Moskau wirft das „Tatarenjoch“ ab.", w: "Stehen an der Ugra" },
  { y: 1492, t: "Granada fällt, Kolumbus erreicht Amerika, Juden aus Spanien vertrieben.", w: "Christoph Kolumbus" },
  { y: 1494, t: "Vertrag von Tordesillas: Spanien und Portugal teilen die Welt.", w: "Vertrag von Tordesillas" },
  { y: 1498, t: "Vasco da Gama erreicht Indien um Afrika herum.", w: "Vasco da Gama" },
  { y: 1500, t: "Cabral landet in Brasilien.", w: "Pedro Álvares Cabral" },
  { y: 1517, t: "Luthers 95 Thesen – Beginn der Reformation.", w: "95 Thesen" },
  { y: 1519, t: "Karl V. wird Kaiser; Cortés landet in Mexiko; Magellans Flotte bricht auf.", w: "Karl V. (HRR)" },
  { y: 1521, t: "Luther in Worms („Hier stehe ich“); Tenochtitlán fällt.", w: "Reichstag zu Worms (1521)" },
  { y: 1525, t: "Deutscher Bauernkrieg blutig niedergeschlagen.", w: "Deutscher Bauernkrieg" },
  { y: 1526, t: "Mohács: Ungarn fällt an die Osmanen; Babur gründet das Mogulreich.", w: "Schlacht bei Mohács (1526)" },
  { y: 1529, t: "Erste Türkenbelagerung Wiens scheitert.", w: "Erste Wiener Türkenbelagerung" },
  { y: 1533, t: "Pizarro lässt Inka Atahualpa hinrichten – das Inkareich fällt.", w: "Atahualpa" },
  { y: 1534, t: "Heinrich VIII. bricht mit Rom – Anglikanische Kirche.", w: "Heinrich VIII. (England)" },
  { y: 1543, t: "Kopernikus: Die Erde kreist um die Sonne. Vesals Anatomie erscheint.", w: "Nikolaus Kopernikus" },
  { y: 1545, t: "Konzil von Trient (Gegenreformation); Silberberg von Potosí entdeckt.", w: "Konzil von Trient" },

  // ===== Konfessionszeitalter =====
  { y: 1555, t: "Augsburger Religionsfriede: „Cuius regio, eius religio“.", w: "Augsburger Reichs- und Religionsfrieden" },
  { y: 1556, t: "Akbar der Große wird Mogulkaiser; Philipp II. König von Spanien.", w: "Akbar (Großmogul)" },
  { y: 1562, t: "Hugenottenkriege in Frankreich beginnen (bis 1598).", w: "Hugenottenkriege" },
  { y: 1568, t: "Aufstand der Niederlande gegen Spanien – der Achtzigjährige Krieg.", w: "Achtzigjähriger Krieg" },
  { y: 1571, t: "Lepanto: christliche Flotte besiegt die Osmanen.", w: "Seeschlacht von Lepanto" },
  { y: 1572, t: "Bartholomäusnacht: Massaker an den Hugenotten in Paris.", w: "Bartholomäusnacht" },
  { y: 1588, t: "Untergang der Spanischen Armada.", w: "Spanische Armada" },
  { y: 1598, t: "Edikt von Nantes: begrenzte Glaubensfreiheit in Frankreich.", w: "Edikt von Nantes" },
  { y: 1600, t: "Englische East India Company gegründet; Giordano Bruno verbrannt.", w: "Britische Ostindien-Kompanie" },
  { y: 1602, t: "Niederländische VOC – die erste Aktiengesellschaft der Welt.", w: "Niederländische Ostindien-Kompanie" },
  { y: 1603, t: "Tokugawa Ieyasu wird Shogun – 250 Jahre Frieden und Abschottung Japans.", w: "Tokugawa Ieyasu" },
  { y: 1607, t: "Jamestown: erste dauerhafte englische Siedlung in Amerika.", w: "Jamestown (Virginia)" },
  { y: 1618, t: "Prager Fenstersturz – der Dreißigjährige Krieg beginnt.", w: "Dreißigjähriger Krieg" },
  { y: 1620, t: "Mayflower: die Pilgerväter landen in Neuengland.", w: "Mayflower" },
  { y: 1631, t: "Zerstörung Magdeburgs – Synonym für Kriegsgräuel.", w: "Magdeburger Hochzeit" },
  { y: 1632, t: "Gustav Adolf fällt bei Lützen.", w: "Schlacht bei Lützen" },
  { y: 1633, t: "Galilei muss vor der Inquisition widerrufen.", w: "Galileo Galilei" },
  { y: 1642, t: "Englischer Bürgerkrieg beginnt: Parlament gegen König.", w: "Englischer Bürgerkrieg" },
  { y: 1644, t: "Mandschu nehmen Peking – Beginn der Qing-Dynastie.", w: "Qing-Dynastie" },
  { y: 1648, t: "Westfälischer Friede: Ende des Dreißigjährigen Kriegs, neue Staatenordnung.", w: "Westfälischer Friede" },

  // ===== Absolutismus =====
  { y: 1649, t: "England richtet König Karl I. hin – Cromwells Republik.", w: "Karl I. (England)" },
  { y: 1651, t: "Hobbes' „Leviathan“: Rechtfertigung des starken Staates.", w: "Leviathan (Thomas Hobbes)" },
  { y: 1652, t: "Niederländer gründen Kapstadt.", w: "Kapstadt" },
  { y: 1661, t: "Ludwig XIV. übernimmt die Alleinregierung – „L'État, c'est moi“.", w: "Ludwig XIV." },
  { y: 1666, t: "Großer Brand von London; Newtons „Wunderjahre“.", w: "Großer Brand von London" },
  { y: 1683, t: "Zweite Türkenbelagerung Wiens – Entsatz durch Jan Sobieski.", w: "Zweite Wiener Türkenbelagerung" },
  { y: 1685, t: "Ludwig XIV. widerruft das Edikt von Nantes – Hugenotten fliehen.", w: "Edikt von Fontainebleau" },
  { y: 1687, t: "Newtons „Principia“: das Universum als berechenbares Uhrwerk.", w: "Philosophiae Naturalis Principia Mathematica" },
  { y: 1688, t: "Glorious Revolution: das Parlament siegt über die Krone.", w: "Glorious Revolution" },
  { y: 1689, t: "Bill of Rights; Peter der Große übernimmt in Russland.", w: "Bill of Rights (England)" },
  { y: 1700, t: "Großer Nordischer Krieg beginnt (bis 1721).", w: "Großer Nordischer Krieg" },
  { y: 1701, t: "Preußen wird Königreich; Spanischer Erbfolgekrieg beginnt.", w: "Königreich Preußen" },
  { y: 1703, t: "Peter der Große gründet Sankt Petersburg im Sumpf.", w: "Sankt Petersburg" },
  { y: 1709, t: "Poltawa: Russland bricht Schwedens Großmachtstellung.", w: "Schlacht bei Poltawa" },
  { y: 1713, t: "Friede von Utrecht: Frankreichs Vormacht wird eingehegt.", w: "Friede von Utrecht" },
  { y: 1715, t: "Tod Ludwigs XIV. nach 72 Regierungsjahren.", w: "Ludwig XIV." },

  // ===== Aufklärung =====
  { y: 1721, t: "Friede von Nystad: Russland ist Ostseemacht.", w: "Frieden von Nystad" },
  { y: 1740, t: "Friedrich II. und Maria Theresia treten an – Schlesische Kriege.", w: "Friedrich II. (Preußen)" },
  { y: 1748, t: "Montesquieu: „Vom Geist der Gesetze“ – Gewaltenteilung.", w: "Vom Geist der Gesetze" },
  { y: 1751, t: "Erster Band der Encyclopédie erscheint.", w: "Encyclopédie" },
  { y: 1755, t: "Erdbeben von Lissabon erschüttert Europa – auch philosophisch.", w: "Erdbeben von Lissabon 1755" },
  { y: 1756, t: "Siebenjähriger Krieg beginnt – der erste „Weltkrieg“ (bis 1763).", w: "Siebenjähriger Krieg" },
  { y: 1757, t: "Plassey: die East India Company erobert Bengalen.", w: "Schlacht bei Plassey" },
  { y: 1762, t: "Rousseaus „Gesellschaftsvertrag“; Katharina die Große putscht sich an die Macht.", w: "Vom Gesellschaftsvertrag" },
  { y: 1769, t: "Watts verbesserte Dampfmaschine – Motor der Industrialisierung.", w: "James Watt" },
  { y: 1772, t: "Erste Teilung Polens durch Russland, Preußen, Österreich.", w: "Teilungen Polens" },
  { y: 1773, t: "Boston Tea Party – Eskalation in den Kolonien.", w: "Boston Tea Party" },
  { y: 1776, t: "Unabhängigkeitserklärung der USA; Adam Smiths „Wohlstand der Nationen“.", w: "Unabhängigkeitserklärung der Vereinigten Staaten" },
  { y: 1781, t: "Yorktown: die Briten kapitulieren; Kants „Kritik der reinen Vernunft“.", w: "Schlacht von Yorktown" },
  { y: 1787, t: "Verfassung der USA – älteste geltende Verfassung der Welt.", w: "Verfassung der Vereinigten Staaten" },
  { y: 1788, t: "Erste britische Sträflingsflotte erreicht Australien.", w: "First Fleet" },

  // ===== Revolution & Napoleon =====
  { y: 1789, t: "14. Juli: Sturm auf die Bastille; Erklärung der Menschenrechte.", w: "Französische Revolution" },
  { y: 1791, t: "Sklavenaufstand in Haiti; erste französische Verfassung; Mozart stirbt.", w: "Haitianische Revolution" },
  { y: 1792, t: "Kanonade von Valmy; Frankreich wird Republik.", w: "Kanonade von Valmy" },
  { y: 1793, t: "Ludwig XVI. guillotiniert; die Terrorherrschaft beginnt.", w: "Ludwig XVI." },
  { y: 1794, t: "Thermidor: Robespierre selbst unter der Guillotine.", w: "Maximilien de Robespierre" },
  { y: 1798, t: "Napoleons Ägyptenfeldzug – im Gepäck: der Stein von Rosetta.", w: "Ägyptische Expedition" },
  { y: 1799, t: "18. Brumaire: Napoleon putscht sich an die Macht.", w: "Staatsstreich des 18. Brumaire VIII" },
  { y: 1804, t: "Napoleon krönt sich zum Kaiser; Code Civil; Haiti unabhängig.", w: "Napoleon Bonaparte" },
  { y: 1805, t: "Trafalgar und Austerlitz – Seemacht England, Landmacht Frankreich.", w: "Schlacht bei Austerlitz" },
  { y: 1806, t: "Ende des Heiligen Römischen Reichs; Preußen bricht bei Jena zusammen.", w: "Rheinbund" },
  { y: 1808, t: "Spanien erhebt sich – Guerillakrieg gegen Napoleon.", w: "Napoleonische Kriege auf der Iberischen Halbinsel" },
  { y: 1812, t: "Russlandfeldzug: die Grande Armée geht im Winter unter.", w: "Russlandfeldzug 1812" },
  { y: 1813, t: "Völkerschlacht bei Leipzig.", w: "Völkerschlacht bei Leipzig" },
  { y: 1815, t: "Waterloo und Wiener Kongress – Europa wird restauriert.", w: "Wiener Kongress" },

  // ===== 19. Jahrhundert =====
  { y: 1821, t: "Griechischer Unabhängigkeitskrieg beginnt; Napoleon stirbt auf St. Helena.", w: "Griechische Revolution" },
  { y: 1823, t: "Monroe-Doktrin: „Amerika den Amerikanern“.", w: "Monroe-Doktrin" },
  { y: 1825, t: "Erste öffentliche Eisenbahn (Stockton–Darlington).", w: "Geschichte der Eisenbahn" },
  { y: 1830, t: "Julirevolution in Paris; Belgien wird unabhängig.", w: "Julirevolution von 1830" },
  { y: 1833, t: "Großbritannien schafft die Sklaverei im Empire ab.", w: "Slavery Abolition Act 1833" },
  { y: 1839, t: "Erster Opiumkrieg: England erzwingt Chinas Öffnung (bis 1842).", w: "Erster Opiumkrieg" },
  { y: 1845, t: "Große Hungersnot in Irland (bis 1849) – Massenauswanderung.", w: "Große Hungersnot in Irland" },
  { y: 1848, t: "Revolutionen in halb Europa; Kommunistisches Manifest erscheint.", w: "Revolutionen 1848/1849" },
  { y: 1853, t: "Krimkrieg beginnt; Perrys „Schwarze Schiffe“ öffnen Japan.", w: "Krimkrieg" },
  { y: 1857, t: "Großer Aufstand in Indien – danach direkte Kronherrschaft.", w: "Indischer Aufstand von 1857" },
  { y: 1859, t: "Darwins „Entstehung der Arten“; Solferino führt zum Roten Kreuz.", w: "Über die Entstehung der Arten" },
  { y: 1861, t: "US-Bürgerkrieg beginnt; Italien geeint; Russland befreit die Leibeigenen.", w: "Sezessionskrieg" },
  { y: 1863, t: "Gettysburg; Emanzipationsproklamation befreit die Sklaven der Südstaaten.", w: "Emanzipations-Proklamation" },
  { y: 1865, t: "Kriegsende, 13. Zusatzartikel, Lincoln ermordet.", w: "Abraham Lincoln" },
  { y: 1866, t: "Königgrätz: Preußen verdrängt Österreich aus Deutschland.", w: "Schlacht bei Königgrätz" },
  { y: 1868, t: "Meiji-Restauration: Japans Blitz-Modernisierung beginnt.", w: "Meiji-Restauration" },
  { y: 1869, t: "Suezkanal eröffnet; erste transkontinentale Eisenbahn der USA.", w: "Sueskanal" },
  { y: 1871, t: "Deutsche Reichsgründung in Versailles; Pariser Kommune niedergeschlagen.", w: "Deutsche Reichsgründung" },

  // ===== Imperialismus =====
  { y: 1876, t: "Bell patentiert das Telefon; Victoria wird Kaiserin von Indien.", w: "Alexander Graham Bell" },
  { y: 1878, t: "Berliner Kongress ordnet den Balkan neu.", w: "Berliner Kongress" },
  { y: 1884, t: "Kongokonferenz in Berlin: Afrika wird aufgeteilt.", w: "Kongokonferenz" },
  { y: 1885, t: "Benz baut das erste Automobil; Leopolds „Kongo-Freistaat“ – ein Gräuelregime.", w: "Kongo-Freistaat" },
  { y: 1894, t: "Dreyfus-Affäre spaltet Frankreich; Chinesisch-Japanischer Krieg.", w: "Dreyfus-Affäre" },
  { y: 1896, t: "Adwa: Äthiopien schlägt Italien; erste moderne Olympische Spiele.", w: "Schlacht von Adua" },
  { y: 1898, t: "Spanisch-Amerikanischer Krieg: die USA werden Kolonialmacht.", w: "Spanisch-Amerikanischer Krieg" },
  { y: 1899, t: "Burenkrieg (bis 1902); Haager Friedenskonferenz.", w: "Zweiter Burenkrieg" },
  { y: 1900, t: "Boxeraufstand in China; Freuds „Traumdeutung“; Plancks Quantenhypothese.", w: "Boxeraufstand" },
  { y: 1903, t: "Erster Motorflug der Brüder Wright.", w: "Brüder Wright" },
  { y: 1904, t: "Völkermord an Herero und Nama in Deutsch-Südwestafrika (bis 1908).", w: "Völkermord an den Herero und Nama" },
  { y: 1905, t: "Japan besiegt Russland; Revolution in Russland; Einsteins Wunderjahr.", w: "Russisch-Japanischer Krieg" },
  { y: 1911, t: "Chinesische Revolution stürzt das Kaiserreich nach 2000 Jahren.", w: "Xinhai-Revolution" },
  { y: 1912, t: "Balkankriege; Untergang der Titanic.", w: "Balkankriege" },

  // ===== Weltkriege =====
  { y: 1914, t: "28. Juni: Attentat von Sarajevo; im August marschiert Europa in den Krieg.", w: "Erster Weltkrieg" },
  { y: 1915, t: "Völkermord an den Armeniern; Gallipoli; Giftgas bei Ypern.", w: "Völkermord an den Armeniern" },
  { y: 1916, t: "Verdun und Somme: je ~1 Million Opfer, kaum Geländegewinn.", w: "Schlacht um Verdun" },
  { y: 1917, t: "USA treten ein; Oktoberrevolution in Russland.", w: "Oktoberrevolution" },
  { y: 1918, t: "Waffenstillstand; Novemberrevolution; Spanische Grippe (bis zu 50 Mio. Tote).", w: "Spanische Grippe" },
  { y: 1919, t: "Versailler Vertrag; Weimarer Verfassung; Amritsar-Massaker.", w: "Friedensvertrag von Versailles" },
  { y: 1922, t: "Mussolinis Marsch auf Rom; Gründung der UdSSR; Ägypten formell unabhängig.", w: "Marsch auf Rom" },
  { y: 1923, t: "Hyperinflation in Deutschland; Hitlerputsch scheitert; Türkei wird Republik.", w: "Deutsche Inflation 1914 bis 1923" },
  { y: 1929, t: "Schwarzer Donnerstag: Beginn der Weltwirtschaftskrise.", w: "Schwarzer Donnerstag" },
  { y: 1930, t: "Gandhis Salzmarsch gegen die britische Kolonialherrschaft.", w: "Salzmarsch" },
  { y: 1931, t: "Japan besetzt die Mandschurei – der Weg in den Pazifikkrieg beginnt.", w: "Mandschurei-Krise" },
  { y: 1933, t: "Hitler wird Kanzler – in Monaten zur Diktatur; Roosevelts New Deal.", w: "Machtergreifung" },
  { y: 1935, t: "Nürnberger Rassegesetze; Italien überfällt Äthiopien.", w: "Nürnberger Gesetze" },
  { y: 1936, t: "Spanischer Bürgerkrieg beginnt; Remilitarisierung des Rheinlands.", w: "Spanischer Bürgerkrieg" },
  { y: 1937, t: "Japan überfällt China – Massaker von Nanking; Guernica bombardiert.", w: "Massaker von Nanking" },
  { y: 1938, t: "„Anschluss“ Österreichs; Münchner Abkommen; Novemberpogrome.", w: "Novemberpogrome 1938" },
  { y: 1939, t: "Hitler-Stalin-Pakt; 1. September: Überfall auf Polen – Zweiter Weltkrieg.", w: "Zweiter Weltkrieg" },
  { y: 1940, t: "Frankreich fällt in sechs Wochen; Luftschlacht um England.", w: "Westfeldzug" },
  { y: 1941, t: "Überfall auf die Sowjetunion; Pearl Harbor – der Krieg wird global.", w: "Unternehmen Barbarossa" },
  { y: 1942, t: "Wannsee-Konferenz; Wende bei Midway, El Alamein und vor Stalingrad.", w: "Wannseekonferenz" },
  { y: 1943, t: "Stalingrad kapituliert; Kursk; Italien fällt ab.", w: "Schlacht von Stalingrad" },
  { y: 1944, t: "D-Day; Attentat vom 20. Juli scheitert.", w: "Operation Overlord" },
  { y: 1945, t: "Kapitulation Deutschlands; Hiroshima und Nagasaki; Gründung der UNO.", w: "Ende des Zweiten Weltkriegs in Europa" },

  // ===== Kalter Krieg =====
  { y: 1947, t: "Truman-Doktrin; Unabhängigkeit und Teilung Indiens.", w: "Truman-Doktrin" },
  { y: 1948, t: "Staatsgründung Israels; Berlin-Blockade; Allgemeine Erklärung der Menschenrechte.", w: "Berlin-Blockade" },
  { y: 1949, t: "NATO; zwei deutsche Staaten; Mao ruft die Volksrepublik aus.", w: "Gründung der Volksrepublik China" },
  { y: 1950, t: "Koreakrieg beginnt (bis 1953).", w: "Koreakrieg" },
  { y: 1953, t: "Stalin stirbt; Aufstand des 17. Juni in der DDR.", w: "Aufstand des 17. Juni" },
  { y: 1955, t: "Warschauer Pakt; Bandung-Konferenz der Blockfreien; Rosa Parks bleibt sitzen.", w: "Rosa Parks" },
  { y: 1956, t: "Ungarn-Aufstand niedergewalzt; Suezkrise.", w: "Ungarischer Volksaufstand" },
  { y: 1957, t: "Sputnik-Schock; Römische Verträge (EWG); Ghana als erste Kolonie Schwarzafrikas frei.", w: "Sputnik 1" },
  { y: 1959, t: "Kubanische Revolution: Castro übernimmt.", w: "Kubanische Revolution" },
  { y: 1960, t: "„Afrikanisches Jahr“: 17 Staaten werden unabhängig.", w: "Afrikanisches Jahr" },
  { y: 1961, t: "Mauerbau in Berlin; Gagarin als erster Mensch im All.", w: "Berliner Mauer" },
  { y: 1962, t: "Kubakrise – die Welt am Rand des Atomkriegs; Algerien unabhängig.", w: "Kubakrise" },
  { y: 1963, t: "„I have a dream“; Kennedy in Dallas ermordet.", w: "Martin Luther King" },
  { y: 1964, t: "Tonkin-Resolution: die USA eskalieren in Vietnam; Civil Rights Act.", w: "Civil Rights Act von 1964" },
  { y: 1966, t: "Mao entfesselt die Kulturrevolution.", w: "Kulturrevolution" },
  { y: 1967, t: "Sechstagekrieg: Israel erobert Westjordanland, Gaza, Golan, Sinai.", w: "Sechstagekrieg" },
  { y: 1968, t: "Prager Frühling niedergewalzt; weltweite Studentenproteste; Tet-Offensive.", w: "Prager Frühling" },
  { y: 1969, t: "Apollo 11: „Ein kleiner Schritt…“ – Menschen auf dem Mond.", w: "Apollo 11" },
  { y: 1973, t: "Jom-Kippur-Krieg und Ölkrise; Pinochet-Putsch in Chile.", w: "Ölpreiskrise" },
  { y: 1975, t: "Saigon fällt – Ende des Vietnamkriegs; KSZE-Schlussakte von Helsinki.", w: "Fall von Saigon" },
  { y: 1978, t: "Deng Xiaoping startet „Reform und Öffnung“ – Chinas Aufstieg beginnt.", w: "Deng Xiaoping" },
  { y: 1979, t: "Islamische Revolution im Iran; UdSSR marschiert in Afghanistan ein.", w: "Islamische Revolution" },
  { y: 1980, t: "Solidarność in Polen – erste freie Gewerkschaft im Ostblock.", w: "Solidarność" },
  { y: 1985, t: "Gorbatschow: Glasnost und Perestroika.", w: "Michail Gorbatschow" },
  { y: 1986, t: "Reaktorkatastrophe von Tschernobyl.", w: "Nuklearkatastrophe von Tschernobyl" },
  { y: 1989, t: "Tian'anmen-Massaker; 9. November: die Berliner Mauer fällt.", w: "Mauerfall" },
  { y: 1990, t: "Deutsche Wiedervereinigung; Mandela frei; Irak überfällt Kuwait.", w: "Deutsche Wiedervereinigung" },

  // ===== Globalisierung =====
  { y: 1991, t: "Golfkrieg; Jugoslawien zerfällt; Dezember: Ende der Sowjetunion.", w: "Zerfall der Sowjetunion" },
  { y: 1993, t: "EU gegründet (Maastricht); Oslo-Abkommen Israel–PLO.", w: "Vertrag von Maastricht" },
  { y: 1994, t: "Völkermord in Ruanda (~800.000 Tote); Mandela Präsident Südafrikas.", w: "Völkermord in Ruanda" },
  { y: 1995, t: "Srebrenica; Dayton beendet den Bosnienkrieg; WTO gegründet.", w: "Massaker von Srebrenica" },
  { y: 1997, t: "Hongkong zurück an China; Asienkrise.", w: "Übergabe Hongkongs" },
  { y: 1999, t: "Euro eingeführt (Buchgeld); Kosovokrieg; Putin übernimmt in Russland.", w: "Kosovokrieg" },
  { y: 2001, t: "11. September; Krieg in Afghanistan; China tritt der WTO bei.", w: "Terroranschläge am 11. September 2001" },
  { y: 2003, t: "Irakkrieg – ohne UN-Mandat, mit langen Folgen.", w: "Irakkrieg" },
  { y: 2004, t: "EU-Osterweiterung um zehn Staaten; Tsunami im Indischen Ozean.", w: "EU-Erweiterung 2004" },
  { y: 2007, t: "iPhone vorgestellt; US-Immobilienkrise beginnt.", w: "iPhone" },
  { y: 2008, t: "Lehman-Pleite: globale Finanzkrise; Obama gewählt.", w: "Weltfinanzkrise 2007–2008" },
  { y: 2010, t: "Arabischer Frühling beginnt in Tunesien.", w: "Arabischer Frühling" },

  // ===== Vor- und Frühgeschichte =====
  { y: -9500, t: "Göbekli Tepe: Jäger und Sammler errichten die ältesten bekannten Tempelanlagen – Religion vor der Landwirtschaft.", w: "Göbekli Tepe" },
  { y: -9000, t: "Jericho wird besiedelt – eine der ältesten dauerhaft bewohnten Städte der Welt.", w: "Jericho" },
  { y: -8000, t: "Neolithische Revolution im Fruchtbaren Halbmond: Menschen domestizieren Weizen, Gerste, Schafe und Ziegen.", w: "Neolithische Revolution" },
  { y: -7000, t: "Reisanbau beginnt im Jangtse-Tal – Grundlage der chinesischen Zivilisation.", w: "Reis" },
  { y: -6500, t: "Çatalhöyük in Anatolien: eine der größten frühen Siedlungen, dicht gedrängt ohne Straßen.", w: "Çatalhöyük" },
  { y: -5000, t: "Erste Kupferverarbeitung im Nahen Osten – Übergang von der Steinzeit zur Metallzeit beginnt.", w: "Kupferzeit" },
  { y: -3500, t: "Erfindung des Rades in Mesopotamien; erste Stadtstaaten Sumers entstehen.", w: "Rad" },

  // ===== Mehr zu Ägypten, Mesopotamien, Nahost =====
  { y: -1595, t: "Hethiter plündern Babylon – das Reich Hammurapis geht unter.", w: "Hethiter" },
  { y: -1200, t: "Ramses III. schlägt die Seevölker zurück – letzter Höhepunkt der ägyptischen Militärmacht.", w: "Ramses III." },
  { y: -900, t: "Königreich Kusch/Nubien erstarkt südlich Ägyptens – später erobert es Ägypten selbst (25. Dynastie).", w: "Kusch (Reich)" },
  { y: -814, t: "Phönizische Seefahrer aus Tyros gründen Karthago an der nordafrikanischen Küste.", w: "Karthago" },
  { y: -700, t: "Urartu und Phrygien blühen in Kleinasien; der sagenhafte König Midas regiert.", w: "Urartu" },
  { y: -660, t: "Legendäre Reichsgründung Japans durch Kaiser Jimmu (traditionelles Datum).", w: "Jimmu" },

  // ===== Mehr zu Antike & Rom =====
  { y: -1046, t: "Wu von Zhou stürzt die Shang – die Idee vom „Mandat des Himmels“ legitimiert fortan jeden Dynastiewechsel Chinas.", w: "Zhou-Dynastie" },
  { y: -814, t: "Legendäres Gründungsjahr Karthagos durch Dido.", w: "Dido" },
  { y: -600, t: "Zarathustra prägt in Persien die Lehre vom Kampf zwischen Gut und Böse.", w: "Zarathustra" },
  { y: -509, t: "Letzter römischer König Tarquinius Superbus vertrieben.", w: "Lucius Tarquinius Superbus" },
  { y: -450, t: "Zwölftafelgesetz: Roms erstes schriftlich fixiertes Recht, für jeden Bürger einsehbar.", w: "Zwölftafelgesetz" },
  { y: -390, t: "Kelten plündern Rom – ein Trauma, das die römische Expansionspolitik über Jahrhunderte prägt.", w: "Schlacht an der Allia" },
  { y: -256, t: "Qin erobert die letzten Zhou-Gebiete; das Ende der Streitenden Reiche naht.", w: "Zeit der Streitenden Reiche" },
  { y: -230, t: "Rom unterwirft die Kelten Oberitaliens; im Osten wächst das Partherreich zur Großmacht heran.", w: "Partherreich" },
  { y: -140, t: "Han-Kaiser Wu weitet China nach Zentralasien aus und öffnet die Seidenstraße für regelmäßigen Handel.", w: "Han Wudi" },
  { y: -63, t: "Pompeius erobert Jerusalem für Rom – Judäa wird römischer Klientelstaat.", w: "Gnaeus Pompeius Magnus" },
  { y: 43, t: "Rom erobert Britannien; im selben Jahrzehnt entsteht das Königreich Aksum in Ostafrika.", w: "Aksumitisches Reich" },
  { y: 184, t: "Aufstand der Gelben Turbane erschüttert Han-China – Beginn des Zerfalls in Warlord-Herrschaften.", w: "Gelbe-Turban-Rebellion" },

  // ===== Mehr zu Spätantike & Frühmittelalter =====
  { y: 220, t: "Ende der Han-Dynastie: China zerfällt in die Drei Reiche (Wei, Shu, Wu).", w: "Drei Reiche" },
  { y: 320, t: "Chandragupta I. gründet das Gupta-Reich – Beginn von Indiens „goldenem Zeitalter“.", w: "Gupta-Reich" },
  { y: 400, t: "Königreich Aksum erreicht seine größte Ausdehnung und prägt eigene Goldmünzen.", w: "Aksumitisches Reich" },
  { y: 415, t: "Hypatia von Alexandria, Mathematikerin und Philosophin, wird von einem christlichen Mob ermordet.", w: "Hypatia" },
  { y: 429, t: "Vandalen unter Geiserich erobern Karthago und Nordafrika – eigenes Königreich mitten im Weströmischen Reich.", w: "Vandalenreich" },
  { y: 500, t: "Königreich Ghana (Wagadu) entsteht in Westafrika – erstes großes Handelsreich der Sahelzone.", w: "Ghana-Reich" },
  { y: 552, t: "Buddhismus erreicht offiziell Japan über Korea.", w: "Buddhismus in Japan" },
  { y: 570, t: "Geburt Mohammeds in Mekka (traditionelles Datum).", w: "Mohammed" },
  { y: 618, t: "Tang-Dynastie gegründet – China wird zur kosmopolitischsten Kultur der damaligen Welt.", w: "Tang-Dynastie" },
  { y: 645, t: "Taika-Reform in Japan: Zentralisierung des Staates nach chinesischem Vorbild.", w: "Taika-Reform" },

  // ===== Mehr zu Hoch- und Spätmittelalter =====
  { y: 794, t: "Japans Hauptstadt zieht nach Heian-kyō (Kyōto) – Beginn der klassischen Heian-Zeit.", w: "Heian-Zeit" },
  { y: 850, t: "Königreich Groß-Simbabwe entsteht im südlichen Afrika, reich durch Gold- und Elfenbeinhandel.", w: "Great Zimbabwe" },
  { y: 860, t: "Waräger (Wikinger) gründen entlang der Flusswege Osteuropas erste Handelsstützpunkte – Vorläufer der Kiewer Rus.", w: "Waräger" },
  { y: 900, t: "Toltekenreich blüht in Zentralmexiko; Maya-Tiefland-Städte werden weitgehend verlassen.", w: "Tolteken" },
  { y: 1000, t: "Songhaireich löst Ghana als dominierende Macht am Niger ab.", w: "Songhaireich" },
  { y: 1054, t: "Seldschuken drängen ins byzantinische Anatolien vor.", w: "Seldschuken" },
  { y: 1099, t: "Kreuzfahrerstaaten Edessa, Antiochia, Tripolis und Jerusalem entstehen an der Levanteküste.", w: "Kreuzfahrerstaaten" },
  { y: 1119, t: "Templerorden gegründet – erster der großen geistlichen Ritterorden.", w: "Templerorden" },
  { y: 1147, t: "Zweiter Kreuzzug scheitert; in Westafrika expandiert das Almoravidenreich bis nach Spanien.", w: "Almoraviden" },
  { y: 1150, t: "Cusco wird Hauptstadt eines aufstrebenden Andenreichs – Vorläufer des späteren Inkareichs.", w: "Cusco" },
  { y: 1180, t: "Kamakura-Shogunat entsteht: Japan wird faktisch von Kriegerklassen statt vom Kaiserhof regiert.", w: "Kamakura-Shōgunat" },
  { y: 1206, t: "Sultanat von Delhi gegründet – erste dauerhafte islamische Großmacht in Nordindien.", w: "Sultanat von Delhi" },
  { y: 1235, t: "Sundiata Keïta gründet das Malireich nach dem Sieg über den Herrscher von Sosso.", w: "Sundiata Keïta" },
  { y: 1252, t: "Florenz prägt den Goldflorin – wird zur Leitwährung des europäischen Fernhandels.", w: "Florin" },
  { y: 1279, t: "Kublai Khan vollendet die Eroberung Chinas – die Song-Dynastie geht unter, die Yuan-Dynastie beginnt.", w: "Yuan-Dynastie" },
  { y: 1298, t: "Marco Polo diktiert im genuesischen Gefängnis seinen Reisebericht „Il Milione“ über China.", w: "Marco Polo" },
  { y: 1299, t: "Osman I. gründet das osmanische Fürstentum in Anatolien.", w: "Osman I." },
  { y: 1336, t: "Vijayanagar-Reich gegründet – letztes großes Hindu-Reich Südindiens.", w: "Vijayanagar-Reich" },
  { y: 1345, t: "Aztekische Gründung Tenochtitláns – auf einer Insel im Texcocosee entsteht die spätere Millionenstadt.", w: "Tenochtitlán" },
  { y: 1370, t: "Timur (Tamerlan) beginnt seine Eroberungszüge von Zentralasien bis nach Indien und Syrien.", w: "Timur" },
  { y: 1398, t: "Timur plündert Delhi – eine der blutigsten Städteeroberungen des Mittelalters.", w: "Timur" },

  // ===== Mehr zu früher Neuzeit =====
  { y: 1440, t: "Songhaireich unter Sunni Ali erreicht seine größte Ausdehnung am Niger.", w: "Songhaireich" },
  { y: 1441, t: "Portugiesische Schiffe bringen erste versklavte Afrikaner nach Europa – Beginn des atlantischen Sklavenhandels.", w: "Atlantischer Sklavenhandel" },
  { y: 1467, t: "Ōnin-Krieg stürzt Japan in die „Sengoku-Zeit“ – ein Jahrhundert Bürgerkrieg zwischen rivalisierenden Daimyō.", w: "Sengoku-Zeit" },
  { y: 1487, t: "Bartolomeu Dias umsegelt das Kap der Guten Hoffnung – der Seeweg nach Indien scheint möglich.", w: "Bartolomeu Dias" },
  { y: 1497, t: "John Cabot erreicht im englischen Auftrag Neufundland.", w: "Johannes Cabot" },
  { y: 1502, t: "Safawidenreich in Persien gegründet – Schiismus wird Staatsreligion.", w: "Safawiden" },
  { y: 1510, t: "Portugal erobert Goa – Ausgangspunkt seines Handelsimperiums in Asien.", w: "Portugiesisch-Indien" },
  { y: 1517, t: "Osmanen erobern Ägypten und die Mamluken – der Sultan wird auch Beschützer der heiligen Stätten Mekka und Medina.", w: "Osmanisch-Mamlukischer Krieg" },
  { y: 1526, t: "Babur besiegt das Sultanat von Delhi bei Panipat – Gründung des Mogulreichs.", w: "Erste Schlacht bei Panipat" },
  { y: 1532, t: "Inka-Bürgerkrieg zwischen Atahualpa und Huáscar schwächt das Reich kurz vor Pizarros Ankunft.", w: "Inka" },
  { y: 1571, t: "Spanien gründet Manila – Brücke zwischen amerikanischem Silber und chinesischer Seide.", w: "Manila-Galeone" },
  { y: 1582, t: "Papst Gregor XIII. führt den Gregorianischen Kalender ein.", w: "Gregorianischer Kalender" },
  { y: 1600, t: "Sekigahara: Tokugawa Ieyasu siegt in Japans entscheidender Schlacht – der Weg zum Shogunat ist frei.", w: "Schlacht bei Sekigahara" },
  { y: 1613, t: "„Zeit der Wirren“ endet in Russland – die Romanow-Dynastie besteigt den Thron (bis 1917).", w: "Romanow" },
  { y: 1637, t: "Tulpenmanie in den Niederlanden – eine der ersten dokumentierten Spekulationsblasen der Geschichte.", w: "Tulpenmanie" },
  { y: 1639, t: "Japan schließt sich fast vollständig ab (Sakoku) – 200 Jahre Isolation beginnen.", w: "Sakoku" },
  { y: 1644, t: "Li Zichengs Bauernaufstand stürzt die Ming-Dynastie; Mandschu nehmen Peking und gründen die Qing-Dynastie.", w: "Qing-Dynastie" },
  { y: 1652, t: "Niederländische Kapkolonie gegründet – erste dauerhafte europäische Siedlung im südlichen Afrika.", w: "Kapkolonie" },
  { y: 1670, t: "Shivaji krönt sich zum Chhatrapati – Gründung des Marathenreichs, das später das Mogulreich herausfordert.", w: "Shivaji" },
  { y: 1682, t: "Ludwig XIV. zieht mit dem Hof nach Versailles – Symbol der absolutistischen Machtinszenierung.", w: "Schloss Versailles" },
  { y: 1690, t: "Britische East India Company gründet Kalkutta.", w: "Kalkutta" },

  // ===== Mehr zu Aufklärung, Revolution, 19. Jahrhundert =====
  { y: 1707, t: "Act of Union: England und Schottland vereinigen sich zum Königreich Großbritannien.", w: "Act of Union 1707" },
  { y: 1729, t: "Nader Schah besteigt den persischen Thron und stellt kurzzeitig ein Großreich bis Indien wieder her.", w: "Nader Schah" },
  { y: 1738, t: "Nader Schah plündert Delhi und nimmt den Pfauenthron als Beute mit nach Persien.", w: "Pfauenthron" },
  { y: 1744, t: "Bündnis zwischen Ibn Saud und dem Prediger al-Wahhab – Grundstein des heutigen Saudi-Arabien.", w: "Wahhabiten" },
  { y: 1768, t: "Cooks erste Pazifikreise – Vermessung Australiens und Neuseelands für die europäische Kartografie.", w: "James Cook" },
  { y: 1775, t: "Erste Schüsse bei Lexington und Concord – der amerikanische Unabhängigkeitskrieg beginnt.", w: "Schlachten von Lexington und Concord" },
  { y: 1780, t: "Tupac Amaru II. führt den größten indigenen Aufstand gegen die spanische Kolonialherrschaft in Peru an.", w: "Túpac Amaru II." },
  { y: 1789, t: "George Washington wird erster Präsident der USA; in Frankreich beginnt die Revolution.", w: "George Washington" },
  { y: 1799, t: "Rosetta-Stein entdeckt – Schlüssel zur Entzifferung der ägyptischen Hieroglyphen.", w: "Stein von Rosette" },
  { y: 1803, t: "Louisiana Purchase: die USA verdoppeln durch Kauf von Frankreich ihr Staatsgebiet.", w: "Louisiana Purchase" },
  { y: 1804, t: "Sokoto-Kalifat gegründet – wird zum größten westafrikanischen Reich des 19. Jahrhunderts.", w: "Sokoto-Kalifat" },
  { y: 1810, t: "Mexikanischer Unabhängigkeitskrieg beginnt mit dem „Grito de Dolores“.", w: "Mexikanischer Unabhängigkeitskrieg" },
  { y: 1816, t: "Argentinien erklärt die Unabhängigkeit von Spanien.", w: "Argentinische Unabhängigkeitserklärung" },
  { y: 1818, t: "Shaka Zulu formt aus kleinen Clans das mächtige Zulu-Königreich – der „Mfecane“ verändert das südliche Afrika.", w: "Shaka Zulu" },
  { y: 1821, t: "Peru und Mexiko werden unabhängig; in Griechenland beginnt der Aufstand gegen die Osmanen.", w: "Griechische Revolution" },
  { y: 1830, t: "Frankreich beginnt die Eroberung Algeriens; Belgien löst sich von den Niederlanden.", w: "Eroberung Algeriens durch Frankreich" },
  { y: 1835, t: "Buren beginnen den „Großen Treck“ aus der britischen Kapkolonie ins Landesinnere Südafrikas.", w: "Großer Treck" },
  { y: 1836, t: "Schlacht von Alamo im texanischen Unabhängigkeitskrieg gegen Mexiko.", w: "Belagerung von Alamo" },
  { y: 1838, t: "„Trail of Tears“: die USA deportieren die Cherokee gewaltsam nach Westen, tausende sterben.", w: "Pfad der Tränen" },
  { y: 1842, t: "Erster Opiumkrieg endet: China tritt Hongkong an Großbritannien ab.", w: "Vertrag von Nanking" },
  { y: 1848, t: "Kalifornischer Goldrausch beginnt; Marx und Engels veröffentlichen das Kommunistische Manifest.", w: "Kalifornischer Goldrausch" },
  { y: 1850, t: "Taiping-Aufstand beginnt in China – mit ~20 Millionen Toten der blutigste Bürgerkrieg der Geschichte.", w: "Taiping-Aufstand" },
  { y: 1858, t: "Vietnam gerät unter französischen Kolonialdruck; Großmogul-Herrschaft in Indien offiziell beendet.", w: "Französisch-Indochina" },
  { y: 1860, t: "Vereinigung Italiens durch Garibaldis „Zug der Tausend“ nimmt Fahrt auf.", w: "Zug der Tausend" },
  { y: 1867, t: "Österreichisch-ungarischer Ausgleich: die Doppelmonarchie entsteht; Kanada wird Dominion.", w: "Österreichisch-Ungarischer Ausgleich" },
  { y: 1868, t: "Meiji-Restauration: das Shogunat fällt, Japan modernisiert sich radikal.", w: "Meiji-Restauration" },
  { y: 1870, t: "Suezkanal drei Jahre in Betrieb; Frankreich verliert den Krieg gegen Preußen und wird Republik.", w: "Deutsch-Französischer Krieg" },
  { y: 1873, t: "„Gründerkrach“ beendet den europäischen Wirtschaftsboom – erste globale Finanzkrise des Industriezeitalters.", w: "Gründerkrach" },
  { y: 1879, t: "Chile gewinnt den Salpeterkrieg gegen Bolivien und Peru – Bolivien verliert seinen Meerzugang bis heute.", w: "Salpeterkrieg" },
  { y: 1885, t: "Indischer Nationalkongress gegründet – Keimzelle der späteren Unabhängigkeitsbewegung.", w: "Indischer Nationalkongress" },
  { y: 1893, t: "Neuseeland führt als erstes Land der Welt das Frauenwahlrecht ein.", w: "Frauenwahlrecht" },
  { y: 1896, t: "Erste moderne Olympische Spiele in Athen; Äthiopien schlägt bei Adwa die italienische Kolonialarmee.", w: "Olympische Sommerspiele 1896" },

  // ===== Mehr zum 20. Jahrhundert =====
  { y: 1905, t: "Einsteins „Wunderjahr“: spezielle Relativitätstheorie und Photoeffekt verändern die Physik.", w: "Albert Einstein" },
  { y: 1908, t: "Jungtürkische Revolution zwingt den Sultan zur Verfassung; erstes Fließband bei Ford revolutioniert die Industrie.", w: "Jungtürken" },
  { y: 1910, t: "Mexikanische Revolution beginnt (bis 1920) – Millionen Tote, tiefgreifender sozialer Umbruch.", w: "Mexikanische Revolution" },
  { y: 1912, t: "Titanic sinkt; in China stürzt die Xinhai-Revolution das 2000-jährige Kaiserreich.", w: "Xinhai-Revolution" },
  { y: 1916, t: "Sykes-Picot-Abkommen: Großbritannien und Frankreich teilen den Nahen Osten im Geheimen auf.", w: "Sykes-Picot-Abkommen" },
  { y: 1919, t: "Massaker von Amritsar erschüttert Indien; Bauhaus in Weimar gegründet.", w: "Massaker von Amritsar" },
  { y: 1921, t: "Sowjetunion führt die Neue Ökonomische Politik ein – vorübergehende Lockerung der Planwirtschaft.", w: "Neue Ökonomische Politik" },
  { y: 1928, t: "Erster sowjetischer Fünfjahresplan startet die forcierte Industrialisierung.", w: "Fünfjahrplan" },
  { y: 1932, t: "Saudi-Arabien als Königreich ausgerufen; schwere Dürre löst den „Dust Bowl“ in den USA aus.", w: "Saudi-Arabien" },
  { y: 1934, t: "Maos „Langer Marsch“: die chinesischen Kommunisten entkommen der Einkreisung durch die Nationalisten.", w: "Langer Marsch" },
  { y: 1936, t: "Berliner Olympische Spiele als NS-Propagandaschau; Stalins „Große Säuberung“ beginnt.", w: "Große Säuberung" },
  { y: 1941, t: "Deutsche Truppen belagern Leningrad – die Blockade kostet über eine Million Zivilisten das Leben.", w: "Leningrader Blockade" },
  { y: 1944, t: "Bretton-Woods-Konferenz legt die Nachkriegs-Weltwirtschaftsordnung fest (IWF, Weltbank, Dollar-Leitwährung).", w: "Bretton-Woods-System" },
  { y: 1946, t: "Erster Indochinakrieg beginnt: Vietnam gegen die zurückkehrende französische Kolonialmacht.", w: "Indochinakrieg" },
  { y: 1948, t: "Apartheid wird in Südafrika gesetzlich verankert.", w: "Apartheid" },
  { y: 1952, t: "Ägyptische Freie Offiziere stürzen König Faruq – Nasser übernimmt später die Macht.", w: "Ägyptische Revolution 1952" },
  { y: 1954, t: "Algerienkrieg beginnt – acht Jahre erbitterter Unabhängigkeitskampf gegen Frankreich.", w: "Algerienkrieg" },
  { y: 1955, t: "Bandung-Konferenz: 29 asiatische und afrikanische Staaten gründen die Bewegung der Blockfreien.", w: "Bandung-Konferenz" },
  { y: 1956, t: "Suezkrise: Ägypten verstaatlicht den Suezkanal, die alten Kolonialmächte müssen auf Druck der USA nachgeben.", w: "Suez-Krise" },
  { y: 1958, t: "Große Chinesische Hungersnot beginnt als Folge von Maos „Großem Sprung“ (bis 1962, Millionen Tote).", w: "Große chinesische Hungersnot" },
  { y: 1960, t: "„Afrikanisches Jahr“: 17 afrikanische Staaten werden unabhängig, darunter Nigeria und Kongo.", w: "Afrikanisches Jahr" },
  { y: 1965, t: "Indonesien: gescheiterter Putschversuch löst Massaker mit hunderttausenden Toten aus; Malaysia entlässt Singapur in die Unabhängigkeit.", w: "Indonesische Massentötungen 1965–1966" },
  { y: 1967, t: "Biafra-Krieg in Nigeria beginnt – eine der schlimmsten Hungerkatastrophen der Nachkriegszeit.", w: "Biafra-Krieg" },
  { y: 1971, t: "Bangladesch erkämpft die Unabhängigkeit von Pakistan; Nixon beendet die Golddeckung des Dollar.", w: "Bangladesch-Krieg" },
  { y: 1972, t: "Nixon besucht China – Wiederannäherung nach 23 Jahren Funkstille.", w: "Nixons Besuch in der Volksrepublik China 1972" },
  { y: 1975, t: "Rote Khmer erobern Phnom Penh – Beginn des Genozids in Kambodscha (bis 1979, ~1,7 Mio. Tote).", w: "Rote Khmer" },
  { y: 1976, t: "Sojasoldaten-Massaker von Soweto: südafrikanische Polizei erschießt protestierende Schulkinder.", w: "Aufstand von Soweto" },
  { y: 1977, t: "Apple II und erste Massenmarkt-PCs läuten das Computerzeitalter ein.", w: "Apple II" },
  { y: 1980, t: "Iran-Irak-Krieg beginnt (bis 1988) – einer der verlustreichsten Kriege des 20. Jahrhunderts.", w: "Erster Golfkrieg" },
  { y: 1989, t: "Namibia wird nach jahrzehntelangem Befreiungskampf unabhängig von Südafrika.", w: "Namibia" },
  { y: 1993, t: "Ruanda-Bürgerkrieg spitzt sich zu; World Wide Web wird öffentlich freigegeben.", w: "World Wide Web" },
  { y: 1997, t: "Kyoto-Protokoll verabschiedet – erstes internationales Klimaschutzabkommen mit bindenden Zielen.", w: "Kyoto-Protokoll" },
  { y: 1998, t: "Karfreitagsabkommen beendet weitgehend den Nordirlandkonflikt.", w: "Karfreitagsabkommen" },

  // ===== 21. Jahrhundert (über 2010 hinaus) =====
  { y: 2011, t: "Arabischer Frühling erfasst Ägypten, Libyen und Syrien; Fukushima-Reaktorkatastrophe nach Tsunami in Japan.", w: "Nuklearkatastrophe von Fukushima" },
  { y: 2011, t: "Bürgerkrieg in Syrien beginnt aus Protesten gegen Assad – bis heute eine der größten humanitären Katastrophen.", w: "Bürgerkrieg in Syrien" },
  { y: 2014, t: "Russland annektiert die Krim; Krieg im Donbas beginnt.", w: "Annexion der Krim 2014" },
  { y: 2015, t: "Pariser Klimaabkommen verabschiedet; „Flüchtlingskrise“ erreicht Europa mit über einer Million Ankünften.", w: "Übereinkommen von Paris" },
  { y: 2016, t: "Brexit-Referendum: Großbritannien stimmt für den EU-Austritt; Trump wird US-Präsident gewählt.", w: "Brexit" },
  { y: 2018, t: "#MeToo-Bewegung verändert weltweit den öffentlichen Umgang mit sexueller Gewalt.", w: "MeToo-Bewegung" },
  { y: 2019, t: "Erstes Foto eines Schwarzen Lochs veröffentlicht; Proteste in Hongkong gegen das Auslieferungsgesetz.", w: "Ereignishorizont-Teleskop" },
  { y: 2020, t: "COVID-19-Pandemie legt die Weltwirtschaft lahm; Tod George Floyds löst globale Protestwelle aus.", w: "COVID-19-Pandemie" },
  { y: 2021, t: "Taliban erobern Kabul nach Abzug der US-Truppen – 20 Jahre Krieg in Afghanistan enden abrupt.", w: "Fall von Kabul (2021)" },
  { y: 2022, t: "Russland startet die Vollinvasion der Ukraine – größter Krieg in Europa seit 1945.", w: "Russischer Überfall auf die Ukraine 2022" },
  { y: 2022, t: "ChatGPT veröffentlicht – Beginn eines globalen Wettlaufs um generative Künstliche Intelligenz.", w: "ChatGPT" },
  { y: 2023, t: "Hamas-Angriff auf Israel und der folgende Gaza-Krieg eskalieren den Nahostkonflikt erneut.", w: "Angriff der Hamas auf Israel 2023" }
];
