// Ereignis-Marker auf der Karte. show: [vonJahr, bisJahr] = in welchen
// Karten-Snapshots der Marker sichtbar ist (einschließlich).
// icon: ⚔️ Schlacht/Krieg · 💡 Idee/Erfindung · 👑 Herrschaft/Politik · ⛪ Religion · 🚢 Entdeckung · 🔥 Katastrophe/Umbruch

const EVENTS = [
  // ===== Antike =====
  { lat: 29.98, lng: 31.13, icon: "👑", show: [-3000, -2000], title: "Pyramiden von Gizeh (~2560 v. Chr.)",
    text: "Die Große Pyramide des Cheops bleibt fast 4000 Jahre das höchste Bauwerk der Welt – Ausdruck der Macht der Pharaonen und der Organisationskraft des ägyptischen Staates.", wiki: "Pyramiden von Gizeh" },
  { lat: 32.54, lng: 44.42, icon: "💡", show: [-2000, -1500], title: "Codex Hammurapi (~1750 v. Chr.)",
    text: "In Babylon lässt Hammurapi eines der ersten großen Gesetzeswerke in Stein meißeln – „Auge um Auge“: Recht wird öffentlich und überprüfbar.", wiki: "Codex Hammurapi" },
  { lat: 34.57, lng: 36.51, icon: "⚔️", show: [-1500, -1000], title: "Schlacht von Kadesch (~1274 v. Chr.)",
    text: "Ägypter gegen Hethiter – die größte Streitwagenschlacht der Geschichte endet im ersten schriftlich überlieferten Friedensvertrag.", wiki: "Schlacht bei Kadesch" },
  { lat: 37.64, lng: 21.63, icon: "🏛️", show: [-1000, -700], title: "Erste Olympische Spiele (776 v. Chr.)",
    text: "In Olympia beginnt die panhellenische Tradition der Spiele – die Griechen rechnen fortan in Olympiaden.", wiki: "Olympische Spiele der Antike" },
  { lat: 41.89, lng: 12.48, icon: "👑", show: [-1000, -700], title: "Gründung Roms (753 v. Chr., Legende)",
    text: "„Ab urbe condita“ – von der Sage um Romulus und Remus bis zum Weltreich: Hier beginnt die Geschichte der ewigen Stadt.", wiki: "Gründung Roms" },
  { lat: 31.78, lng: 35.22, icon: "⛪", show: [-700, -500], title: "Babylonisches Exil (587 v. Chr.)",
    text: "Nebukadnezar II. zerstört Jerusalem und den Tempel. Im Exil formt sich die hebräische Bibel – und ein Gott, der an keinen Ort gebunden ist.", wiki: "Babylonisches Exil" },
  { lat: 24.70, lng: 84.99, icon: "⛪", show: [-700, -400], title: "Buddha erlangt Erleuchtung (~528 v. Chr.)",
    text: "Unter dem Bodhi-Baum von Bodh Gaya findet Siddhartha Gautama den „mittleren Weg“ – der Buddhismus wird eine Weltreligion.", wiki: "Siddhartha Gautama" },
  { lat: 35.60, lng: 116.99, icon: "💡", show: [-700, -400], title: "Konfuzius lehrt (~500 v. Chr.)",
    text: "In Lu (Qufu) entwickelt Konfuzius seine Ethik von Harmonie, Bildung und gutem Regieren – bis heute Chinas prägendste Denktradition.", wiki: "Konfuzius" },
  { lat: 38.15, lng: 23.96, icon: "⚔️", show: [-500, -400], title: "Perserkriege: Marathon & Salamis (490/480 v. Chr.)",
    text: "Die kleinen griechischen Poleis schlagen die persische Supermacht zurück – Athen steigt zur See- und Kulturmacht auf.", wiki: "Perserkriege" },
  { lat: 37.97, lng: 23.73, icon: "🏛️", show: [-500, -400], title: "Blüte Athens (5. Jh. v. Chr.)",
    text: "Demokratie unter Perikles, Parthenon, Tragödie, Sokrates auf dem Marktplatz – das „Goldene Zeitalter“ einer einzigen Stadt prägt Europa bis heute.", wiki: "Attische Demokratie" },
  { lat: 36.56, lng: 43.44, icon: "⚔️", show: [-400, -300], title: "Gaugamela (331 v. Chr.)",
    text: "Alexander der Große vernichtet das persische Heer des Dareios – das Achämenidenreich fällt an einen 25-Jährigen.", wiki: "Schlacht von Gaugamela" },
  { lat: 31.20, lng: 29.92, icon: "💡", show: [-323, -100], title: "Bibliothek von Alexandria (~300 v. Chr.)",
    text: "Die Ptolemäer sammeln das Wissen der Welt: Euklid, Archimedes und Eratosthenes (er berechnet den Erdumfang!) machen Alexandria zum Wissenschaftszentrum der Antike.", wiki: "Bibliothek von Alexandria" },
  { lat: 34.38, lng: 109.28, icon: "👑", show: [-300, -100], title: "Chinas Einigung (221 v. Chr.)",
    text: "Qin Shihuangdi eint die Streitenden Reiche, normiert Schrift, Maße und Münzen, baut Mauer und Terrakotta-Armee – das Kaiserreich hält 2000 Jahre.", wiki: "Qin Shihuangdi" },
  { lat: 41.30, lng: 16.13, icon: "⚔️", show: [-300, -200], title: "Cannae (216 v. Chr.)",
    text: "Hannibal vernichtet das größte Heer, das Rom je aufstellte – doch Rom kapituliert nicht: Zähigkeit und Bündnissystem gewinnen am Ende den Krieg.", wiki: "Schlacht von Cannae" },
  { lat: 36.85, lng: 10.32, icon: "🔥", show: [-200, -100], title: "Zerstörung Karthagos (146 v. Chr.)",
    text: "„Carthago delenda est“ – Rom radiert seinen Rivalen aus. Im selben Jahr fällt Korinth: Das Mittelmeer wird zum „mare nostrum“.", wiki: "Dritter Punischer Krieg" },
  { lat: 41.89, lng: 12.48, icon: "👑", show: [-100, -1], title: "Caesars Ermordung (44 v. Chr.)",
    text: "Die Iden des März: Der Diktator stirbt im Senat – doch statt der Republik kommt der Bürgerkrieg, und am Ende Augustus' Kaisertum.", wiki: "Gaius Iulius Caesar" },
  { lat: 31.78, lng: 35.22, icon: "⛪", show: [-1, 100], title: "Jesus von Nazareth (~30 n. Chr.)",
    text: "Die Kreuzigung eines Wanderpredigers in Jerusalem wird zum Ausgangspunkt der größten Religion der Welt.", wiki: "Jesus von Nazaret" },
  { lat: 52.41, lng: 8.13, icon: "⚔️", show: [-1, 100], title: "Varusschlacht (9 n. Chr.)",
    text: "Arminius vernichtet drei römische Legionen im Teutoburger Wald – Rom gibt die Expansion über den Rhein auf; die Germania bleibt unerobert.", wiki: "Varusschlacht" },
  { lat: 40.75, lng: 14.49, icon: "🔥", show: [100, 100], title: "Vesuvausbruch – Pompeji (79 n. Chr.)",
    text: "Asche konserviert eine römische Stadt mitsamt Alltag – für die Nachwelt das detaillierteste Fenster in die Antike.", wiki: "Pompeji" },
  { lat: 34.62, lng: 112.45, icon: "💡", show: [100, 200], title: "Erfindung des Papiers (~105 n. Chr.)",
    text: "Der Hofbeamte Cai Lun perfektioniert in Han-China das Papier – der wichtigste Wissensspeicher der Menschheit bis heute.", wiki: "Papier" },
  { lat: 41.01, lng: 28.98, icon: "👑", show: [300, 400], title: "Gründung Konstantinopels (330)",
    text: "Konstantin macht Byzantion zum „Neuen Rom“ – die Stadt am Bosporus wird für 1000 Jahre reichste Metropole der Christenheit.", wiki: "Konstantinopel" },
  { lat: 41.68, lng: 26.56, icon: "⚔️", show: [400, 400], title: "Adrianopel (378)",
    text: "Die Goten vernichten ein römisches Heer samt Kaiser Valens – der Anfang vom Ende der römischen Militärdominanz.", wiki: "Schlacht von Adrianopel (378)" },
  { lat: 48.60, lng: 4.10, icon: "⚔️", show: [400, 500], title: "Katalaunische Felder (451)",
    text: "Römer und Westgoten stoppen gemeinsam Attilas Hunnen – der letzte große Sieg des sterbenden Westroms.", wiki: "Schlacht auf den Katalaunischen Feldern" },
  { lat: 41.89, lng: 12.48, icon: "🔥", show: [500, 500], title: "Ende Westroms (476)",
    text: "Odoaker setzt den Kind-Kaiser Romulus Augustulus ab. Kaum jemand bemerkt das „Epochenereignis“ – der Osten lebt als Byzanz weiter.", wiki: "Romulus Augustulus" },

  // ===== Mittelalter =====
  { lat: 41.01, lng: 28.98, icon: "⛪", show: [500, 600], title: "Hagia Sophia (537)",
    text: "Justinians Kirche der „Heiligen Weisheit“ trägt die größte Kuppel der Welt – Staunen der Zeitgenossen: „Salomo, ich habe dich übertroffen!“", wiki: "Hagia Sophia" },
  { lat: 24.47, lng: 39.61, icon: "⛪", show: [600, 700], title: "Hidschra (622)",
    text: "Mohammeds Auswanderung nach Medina – Jahr 1 der islamischen Zeitrechnung. In 100 Jahren entsteht ein Reich von Spanien bis zum Indus.", wiki: "Hidschra" },
  { lat: 46.90, lng: 0.60, icon: "⚔️", show: [700, 800], title: "Schlacht von Tours und Poitiers (732)",
    text: "Karl Martell stoppt die arabische Expansion nach Westeuropa – die Karolinger steigen zur Schutzmacht der lateinischen Christenheit auf.", wiki: "Schlacht von Tours und Poitiers" },
  { lat: 33.34, lng: 44.40, icon: "💡", show: [800, 1000], title: "Bagdad – Haus der Weisheit (ab 762)",
    text: "Die Abbasiden-Hauptstadt wird zur größten Stadt der Welt; Gelehrte übersetzen und erweitern das Wissen der Antike – Algebra, Medizin, Astronomie.", wiki: "Haus der Weisheit" },
  { lat: 55.68, lng: -1.80, icon: "⚔️", show: [800, 900], title: "Überfall auf Lindisfarne (793)",
    text: "Wikinger plündern das heilige Kloster – der Schock markiert den Beginn der Wikingerzeit: 300 Jahre Raub, Handel und Staatsgründungen.", wiki: "Lindisfarne" },
  { lat: 50.77, lng: 6.08, icon: "👑", show: [800, 800], title: "Kaiserkrönung Karls des Großen (800)",
    text: "Am Weihnachtstag krönt der Papst den Frankenkönig in Rom – der Westen hat wieder einen Kaiser; Aachen wird sein Zentrum.", wiki: "Karl der Große" },
  { lat: 48.30, lng: 10.90, icon: "⚔️", show: [900, 1000], title: "Lechfeldschlacht (955)",
    text: "Otto I. besiegt die Ungarn bei Augsburg – die Reiterüberfälle enden, Ungarn wird christlich, Otto 962 Kaiser: Geburt des Heiligen Römischen Reichs.", wiki: "Schlacht auf dem Lechfeld" },
  { lat: 50.45, lng: 30.52, icon: "⛪", show: [1000, 1000], title: "Taufe der Kiewer Rus (988)",
    text: "Großfürst Wladimir nimmt das orthodoxe Christentum aus Byzanz an – die religiöse und kulturelle Weichenstellung Osteuropas.", wiki: "Wladimir I." },
  { lat: 51.60, lng: -55.50, icon: "🚢", show: [1000, 1000], title: "Wikinger in Amerika (~1000)",
    text: "Leif Eriksson erreicht „Vinland“ (Neufundland) – 500 Jahre vor Kolumbus. Die Siedlung bleibt Episode, der Beweis steht in L'Anse aux Meadows.", wiki: "Leif Eriksson" },
  { lat: 50.91, lng: 0.49, icon: "⚔️", show: [1000, 1100], title: "Schlacht von Hastings (1066)",
    text: "Wilhelm der Eroberer nimmt England – normannischer Adel, Feudalordnung und tausende französische Wörter prägen das Land für immer.", wiki: "Schlacht bei Hastings" },
  { lat: 39.15, lng: 42.54, icon: "⚔️", show: [1100, 1100], title: "Manzikert (1071)",
    text: "Die Seldschuken schlagen Byzanz vernichtend – Anatolien wird türkisch, und der Hilferuf des Kaisers löst die Kreuzzüge aus.", wiki: "Schlacht bei Manzikert" },
  { lat: 44.43, lng: 10.46, icon: "👑", show: [1100, 1100], title: "Gang nach Canossa (1077)",
    text: "Kaiser Heinrich IV. büßt barfuß im Schnee vor Papst Gregor VII. – Höhepunkt des Machtkampfs zwischen weltlicher und geistlicher Gewalt.", wiki: "Gang nach Canossa" },
  { lat: 44.49, lng: 11.34, icon: "💡", show: [1100, 1200], title: "Erste Universität – Bologna (1088)",
    text: "Studenten organisieren sich zur „universitas“ – Paris, Oxford und Dutzende weitere folgen: Europas Wissensmaschine startet.", wiki: "Universität Bologna" },
  { lat: 31.78, lng: 35.22, icon: "⚔️", show: [1100, 1200], title: "Eroberung Jerusalems (1099)",
    text: "Der Erste Kreuzzug endet mit Massaker und Kreuzfahrerstaaten; 1187 erobert Saladin die Stadt zurück.", wiki: "Erster Kreuzzug" },
  { lat: 47.20, lng: 102.80, icon: "👑", show: [1200, 1279], title: "Dschingis Khan geeint (1206)",
    text: "Temüdschin eint die Steppenvölker und schafft in einer Generation das größte Landreich der Geschichte – von Korea bis Ungarn.", wiki: "Dschingis Khan" },
  { lat: 51.44, lng: -0.56, icon: "💡", show: [1200, 1279], title: "Magna Carta (1215)",
    text: "Der englische Adel zwingt König Johann, Rechte schriftlich zu garantieren – Keimzelle der Idee, dass auch der Herrscher unter dem Gesetz steht.", wiki: "Magna Carta" },
  { lat: 33.34, lng: 44.40, icon: "🔥", show: [1279, 1279], title: "Zerstörung Bagdads (1258)",
    text: "Die Mongolen vernichten die Kalifenstadt; der Tigris soll schwarz von Tinte gewesen sein – das Ende des Goldenen Zeitalters des Islam.", wiki: "Eroberung von Bagdad (1258)" },
  { lat: 38.19, lng: 15.55, icon: "🔥", show: [1300, 1400], title: "Der Schwarze Tod (1347–1352)",
    text: "Über Messina erreicht die Pest Europa und tötet ein Drittel der Bevölkerung – Löhne steigen, der Feudalismus erodiert, Pogrome suchen Sündenböcke.", wiki: "Schwarzer Tod" },
  { lat: 42.63, lng: 21.10, icon: "⚔️", show: [1400, 1400], title: "Schlacht auf dem Amselfeld (1389)",
    text: "Die Osmanen brechen die serbische Macht – der Balkan wird für 500 Jahre osmanisch; das Datum prägt serbische Identität bis heute.", wiki: "Schlacht auf dem Amselfeld" },
  { lat: 47.90, lng: 1.90, icon: "⚔️", show: [1400, 1492], title: "Jeanne d'Arc bei Orléans (1429)",
    text: "Ein 17-jähriges Bauernmädchen wendet den Hundertjährigen Krieg – 1431 als Ketzerin verbrannt, später heiliggesprochen.", wiki: "Jeanne d’Arc" },
  { lat: 50.00, lng: 8.27, icon: "💡", show: [1400, 1492], title: "Gutenbergs Buchdruck (~1450)",
    text: "Bewegliche Lettern machen Bücher massenhaft und billig – ohne diese Medienrevolution keine Reformation, keine Aufklärung.", wiki: "Johannes Gutenberg" },
  { lat: 41.01, lng: 28.98, icon: "🔥", show: [1492, 1492], title: "Fall Konstantinopels (1453)",
    text: "Mehmed II. erobert mit Riesenkanonen das 1000-jährige Byzanz – Gelehrte fliehen mit antiken Handschriften nach Italien und befeuern die Renaissance.", wiki: "Eroberung von Konstantinopel (1453)" },

  // ===== Frühe Neuzeit =====
  { lat: 37.18, lng: -3.60, icon: "👑", show: [1492, 1500], title: "Fall Granadas (1492)",
    text: "Das letzte muslimische Reich Iberiens kapituliert – Ende der Reconquista; im selben Jahr: Vertreibung der Juden und Kolumbus' Aufbruch.", wiki: "Emirat von Granada" },
  { lat: 24.00, lng: -74.50, icon: "🚢", show: [1492, 1500], title: "Kolumbus erreicht Amerika (1492)",
    text: "Auf der Suche nach Indien landet Kolumbus auf den Bahamas – zwei Welten prallen aufeinander; für Amerikas Völker beginnt die Katastrophe.", wiki: "Christoph Kolumbus" },
  { lat: 51.87, lng: 12.65, icon: "⛪", show: [1500, 1530], title: "Luthers 95 Thesen (1517)",
    text: "Ein Mönch in Wittenberg kritisiert den Ablasshandel – dank Buchdruck wird daraus die Spaltung der westlichen Christenheit.", wiki: "95 Thesen" },
  { lat: 19.43, lng: -99.13, icon: "🔥", show: [1500, 1530], title: "Fall Tenochtitláns (1521)",
    text: "Cortés, indigene Verbündete und die Pocken stürzen das Aztekenreich – auf den Trümmern entsteht Mexiko-Stadt.", wiki: "Spanische Eroberung Mexikos" },
  { lat: -53.50, lng: -70.90, icon: "🚢", show: [1530, 1530], title: "Erste Weltumsegelung (1519–1522)",
    text: "Magellans Flotte umrundet erstmals die Erde – von 237 Mann kehren 18 zurück; die Kugelgestalt der Erde ist praktisch bewiesen.", wiki: "Ferdinand Magellan" },
  { lat: -7.16, lng: -78.51, icon: "🔥", show: [1530, 1530], title: "Pizarro in Cajamarca (1532)",
    text: "168 Spanier nehmen den Inka Atahualpa gefangen – ein Raum voll Gold als Lösegeld, dann die Hinrichtung: Das Inkareich fällt.", wiki: "Francisco Pizarro" },
  { lat: 48.21, lng: 16.37, icon: "⚔️", show: [1530, 1530], title: "Erste Türkenbelagerung Wiens (1529)",
    text: "Süleyman der Prächtige steht vor Wien – die Osmanen sind auf dem Höhepunkt; Wetter und Nachschub retten die Stadt.", wiki: "Erste Wiener Türkenbelagerung" },
  { lat: 38.20, lng: 21.30, icon: "⚔️", show: [1600, 1600], title: "Seeschlacht von Lepanto (1571)",
    text: "Die Heilige Liga besiegt die osmanische Flotte – die letzte große Galeerenschlacht bricht den Mythos osmanischer Unbesiegbarkeit zur See.", wiki: "Seeschlacht von Lepanto" },
  { lat: 50.20, lng: -1.50, icon: "⚔️", show: [1600, 1600], title: "Untergang der Armada (1588)",
    text: "Spaniens „unbesiegbare“ Flotte scheitert an England und den Stürmen – der Aufstieg der englischen Seemacht beginnt.", wiki: "Spanische Armada" },
  { lat: 50.09, lng: 14.40, icon: "🔥", show: [1650, 1650], title: "Prager Fenstersturz (1618)",
    text: "Böhmische Adlige werfen kaiserliche Statthalter aus dem Fenster – der Funke, der den Dreißigjährigen Krieg entzündet.", wiki: "Zweiter Prager Fenstersturz" },
  { lat: 52.13, lng: 11.62, icon: "🔥", show: [1650, 1650], title: "Zerstörung Magdeburgs (1631)",
    text: "Kaiserliche Truppen massakrieren ~20.000 Einwohner – „Magdeburgisieren“ wird europaweit zum Wort für totale Verwüstung.", wiki: "Magdeburger Hochzeit" },
  { lat: 51.96, lng: 7.63, icon: "👑", show: [1650, 1650], title: "Westfälischer Friede (1648)",
    text: "In Münster und Osnabrück endet der Dreißigjährige Krieg – Staatensouveränität und Mächtegleichgewicht: die Grundordnung Europas bis heute.", wiki: "Westfälischer Friede" },
  { lat: 48.80, lng: 2.12, icon: "👑", show: [1700, 1715], title: "Versailles (ab 1682)",
    text: "Ludwig XIV. macht das Jagdschloss zur Machtbühne: Der Adel wird im Hofzeremoniell domestiziert – ganz Europa kopiert Sprache, Mode und Architektur.", wiki: "Schloss Versailles" },
  { lat: 48.21, lng: 16.37, icon: "⚔️", show: [1700, 1700], title: "Zweite Türkenbelagerung Wiens (1683)",
    text: "Jan Sobieskis Entsatzheer rettet Wien – die Wende: Die Osmanen verlieren Ungarn, Österreich wird Großmacht.", wiki: "Zweite Wiener Türkenbelagerung" },
  { lat: 49.59, lng: 34.55, icon: "⚔️", show: [1715, 1715], title: "Schlacht bei Poltawa (1709)",
    text: "Peter der Große vernichtet das schwedische Heer Karls XII. – Russland löst Schweden als Ostseemacht ab und tritt in den Kreis der Großmächte.", wiki: "Schlacht bei Poltawa" },
  { lat: 23.80, lng: 88.25, icon: "⚔️", show: [1783, 1783], title: "Schlacht bei Plassey (1757)",
    text: "Die britische Ostindien-Kompanie – eine Handelsfirma! – besiegt den Nawab von Bengalen: Beginn der britischen Herrschaft über Indien.", wiki: "Schlacht bei Plassey" },
  { lat: 39.95, lng: -75.16, icon: "💡", show: [1783, 1783], title: "Unabhängigkeitserklärung der USA (1776)",
    text: "„Alle Menschen sind gleich geschaffen“ – in Philadelphia wird erstmals ein Staat auf Aufklärungsideen gegründet.", wiki: "Unabhängigkeitserklärung der Vereinigten Staaten" },

  // ===== Revolution & 19. Jahrhundert =====
  { lat: 48.85, lng: 2.37, icon: "🔥", show: [1800, 1800], title: "Sturm auf die Bastille (1789)",
    text: "Der 14. Juli wird zum Symbol: Die Französische Revolution stürzt die alte Ordnung – Menschenrechte, Republik, Terror, Napoleon.", wiki: "Sturm auf die Bastille" },
  { lat: 18.54, lng: -72.34, icon: "🔥", show: [1800, 1815], title: "Haitianische Revolution (1791–1804)",
    text: "Versklavte Menschen erkämpfen die einzige erfolgreiche Sklavenrevolution der Geschichte – Haiti wird der erste unabhängige Staat Schwarzer Menschen.", wiki: "Haitianische Revolution" },
  { lat: 36.18, lng: -6.03, icon: "⚔️", show: [1815, 1815], title: "Trafalgar (1805)",
    text: "Nelson zerschlägt die französisch-spanische Flotte und fällt im Sieg – Britanniens Seeherrschaft ist für ein Jahrhundert gesichert.", wiki: "Schlacht von Trafalgar" },
  { lat: 55.75, lng: 37.62, icon: "🔥", show: [1815, 1815], title: "Napoleons Russlandfeldzug (1812)",
    text: "Moskau brennt, der Winter kommt: Von 600.000 Mann der Grande Armée kehren kaum 100.000 zurück – der Anfang vom Ende.", wiki: "Russlandfeldzug 1812" },
  { lat: 50.68, lng: 4.41, icon: "⚔️", show: [1815, 1815], title: "Waterloo (1815)",
    text: "Wellington und Blücher besiegen Napoleon endgültig – der Wiener Kongress ordnet Europa neu; 100 Tage Herrschaft enden auf St. Helena.", wiki: "Schlacht bei Waterloo" },
  { lat: -13.16, lng: -74.22, icon: "👑", show: [1815, 1880], title: "Unabhängigkeit Lateinamerikas (1810–1825)",
    text: "Bolívar und San Martín nutzen die Schwäche Spaniens: Von Mexiko bis Chile entstehen unabhängige Republiken – Ayacucho 1824 ist die letzte Schlacht.", wiki: "Südamerikanische Unabhängigkeitskriege" },
  { lat: 53.48, lng: -2.24, icon: "💡", show: [1815, 1880], title: "Industrielle Revolution (ab ~1770)",
    text: "Dampfmaschine, Fabrik, Eisenbahn (1830 Liverpool–Manchester): In England beginnt die tiefste Umwälzung des menschlichen Lebens seit der Sesshaftwerdung.", wiki: "Industrielle Revolution" },
  { lat: 23.13, lng: 113.26, icon: "⚔️", show: [1880, 1880], title: "Opiumkriege (1839–1860)",
    text: "England erzwingt mit Kanonenbooten Drogenhandel und Vertragshäfen – Beginn von Chinas „Jahrhundert der Demütigung“.", wiki: "Erster Opiumkrieg" },
  { lat: 50.11, lng: 8.68, icon: "🔥", show: [1880, 1880], title: "Revolutionen von 1848",
    text: "Von Paris bis Wien fordern Bürger Verfassung und Nation – die Frankfurter Paulskirche scheitert, doch die Ideen überleben.", wiki: "Deutsche Revolution 1848/1849" },
  { lat: 39.81, lng: -77.23, icon: "⚔️", show: [1880, 1880], title: "Gettysburg (1863)",
    text: "Wendepunkt des Amerikanischen Bürgerkriegs – Lincolns Gettysburg Address definiert Demokratie neu: „government of the people, by the people, for the people“.", wiki: "Schlacht von Gettysburg" },
  { lat: 48.80, lng: 2.12, icon: "👑", show: [1880, 1880], title: "Deutsche Reichsgründung (1871)",
    text: "Nach dem Sieg über Frankreich wird Wilhelm I. im Spiegelsaal von Versailles zum Kaiser proklamiert – eine Demütigung, die Frankreich nie vergisst.", wiki: "Deutsche Reichsgründung" },
  { lat: 52.52, lng: 13.40, icon: "👑", show: [1900, 1900], title: "Berliner Konferenz (1884/85)",
    text: "Die europäischen Mächte teilen Afrika am Verhandlungstisch – Grenzen mit dem Lineal, die den Kontinent bis heute prägen.", wiki: "Kongokonferenz" },
  { lat: 34.56, lng: 129.72, icon: "⚔️", show: [1914, 1914], title: "Tsushima (1905)",
    text: "Japan vernichtet die russische Flotte – erstmals besiegt eine asiatische Macht eine europäische Großmacht; die kolonisierte Welt horcht auf.", wiki: "Seeschlacht bei Tsushima" },

  // ===== 20. Jahrhundert =====
  { lat: 43.86, lng: 18.41, icon: "🔥", show: [1914, 1914], title: "Attentat von Sarajevo (28. Juni 1914)",
    text: "Zwei Schüsse auf den österreichischen Thronfolger – die Julikrise eskaliert, die Bündnisblöcke marschieren: Der Erste Weltkrieg beginnt.", wiki: "Attentat von Sarajevo" },
  { lat: 49.16, lng: 5.38, icon: "⚔️", show: [1920, 1920], title: "Verdun (1916)",
    text: "300 Tage „Blutmühle“: ~700.000 Opfer für wenige Kilometer – Verdun wird zum Symbol des sinnlosen Industriekriegs.", wiki: "Schlacht um Verdun" },
  { lat: 59.94, lng: 30.31, icon: "🔥", show: [1920, 1920], title: "Oktoberrevolution (1917)",
    text: "Lenins Bolschewiki stürmen das Winterpalais in Petrograd – der Kommunismus wird Staatsmacht und prägt das Jahrhundert.", wiki: "Oktoberrevolution" },
  { lat: 40.71, lng: -74.01, icon: "🔥", show: [1930, 1930], title: "Börsencrash – Schwarzer Donnerstag (1929)",
    text: "Die Wall Street kollabiert, die Weltwirtschaftskrise stürzt Millionen ins Elend – und radikalisiert die Politik weltweit.", wiki: "Schwarzer Donnerstag" },
  { lat: 52.52, lng: 13.38, icon: "🔥", show: [1938, 1938], title: "Hitlers Machtergreifung (1933)",
    text: "Legal ernannt, in Monaten zur Diktatur: Reichstagsbrand, Ermächtigungsgesetz, Gleichschaltung – Europas Weg in den Abgrund.", wiki: "Machtergreifung" },
  { lat: 32.06, lng: 118.78, icon: "🔥", show: [1938, 1938], title: "Massaker von Nanking (1937)",
    text: "Japanische Truppen ermorden in Chinas Hauptstadt hunderttausende Zivilisten – der Zweite Weltkrieg hat in Asien längst begonnen.", wiki: "Massaker von Nanking" },
  { lat: 21.36, lng: -157.95, icon: "⚔️", show: [1945, 1945], title: "Pearl Harbor (7. Dezember 1941)",
    text: "Japans Überraschungsangriff zieht die USA in den Krieg – „a date which will live in infamy“.", wiki: "Angriff auf Pearl Harbor" },
  { lat: 48.70, lng: 44.50, icon: "⚔️", show: [1945, 1945], title: "Stalingrad (1942/43)",
    text: "Die 6. Armee geht im Kessel unter – die psychologische und militärische Wende des Kriegs in Europa.", wiki: "Schlacht von Stalingrad" },
  { lat: 50.03, lng: 19.18, icon: "🔥", show: [1945, 1945], title: "Auschwitz – der Holocaust",
    text: "Im größten Vernichtungslager ermorden die Nationalsozialisten über eine Million Menschen; insgesamt sterben sechs Millionen Juden Europas – der Zivilisationsbruch.", wiki: "KZ Auschwitz-Birkenau" },
  { lat: 49.34, lng: -0.85, icon: "⚔️", show: [1945, 1945], title: "D-Day – Normandie (6. Juni 1944)",
    text: "Die größte Landungsoperation der Geschichte öffnet die Westfront – ein Jahr später ist das „Dritte Reich“ Geschichte.", wiki: "Operation Overlord" },
  { lat: 34.39, lng: 132.45, icon: "🔥", show: [1945, 1945], title: "Hiroshima (6. August 1945)",
    text: "Die erste Atombombe tötet auf einen Schlag ~70.000 Menschen – Japan kapituliert; die Menschheit kann sich fortan selbst auslöschen.", wiki: "Atombombenabwürfe auf Hiroshima und Nagasaki" },
  { lat: 28.61, lng: 77.20, icon: "👑", show: [1960, 1960], title: "Indiens Unabhängigkeit (1947)",
    text: "Gandhis gewaltfreier Widerstand siegt – doch die Teilung in Indien und Pakistan kostet Hunderttausende das Leben: Auftakt der weltweiten Dekolonisierung.", wiki: "Teilung Indiens" },
  { lat: 39.90, lng: 116.40, icon: "👑", show: [1960, 1960], title: "Volksrepublik China (1949)",
    text: "Mao ruft auf dem Tian'anmen die Volksrepublik aus – ein Fünftel der Menschheit wird kommunistisch.", wiki: "Volksrepublik China" },
  { lat: 23.10, lng: -82.38, icon: "🔥", show: [1960, 1960], title: "Kubakrise (1962)",
    text: "Sowjetische Raketen auf Kuba – 13 Tage steht die Welt am Rand des Atomkriegs, bis Kennedy und Chruschtschow einlenken.", wiki: "Kubakrise" },
  { lat: 10.78, lng: 106.70, icon: "⚔️", show: [1960, 1994], title: "Vietnamkrieg (~1955–1975)",
    text: "Der große Stellvertreterkrieg des Kalten Kriegs: Millionen Tote, das Trauma der USA – 1975 fällt Saigon.", wiki: "Vietnamkrieg" },
  { lat: 52.52, lng: 13.38, icon: "🔥", show: [1994, 1994], title: "Fall der Berliner Mauer (9. November 1989)",
    text: "Friedliche Revolutionen fegen durch Osteuropa – die Mauer fällt, Deutschland wird 1990 wiedervereinigt, 1991 zerfällt die Sowjetunion.", wiki: "Berliner Mauer" },
  { lat: -33.92, lng: 18.42, icon: "👑", show: [1994, 1994], title: "Ende der Apartheid (1994)",
    text: "Nach 27 Jahren Haft wird Nelson Mandela Präsident Südafrikas – Versöhnung statt Rache als politisches Programm.", wiki: "Nelson Mandela" },
  { lat: 40.71, lng: -74.01, icon: "🔥", show: [2000, 2010], title: "11. September 2001",
    text: "Al-Qaida zerstört das World Trade Center – der „Krieg gegen den Terror“ prägt zwei Jahrzehnte Weltpolitik.", wiki: "Terroranschläge am 11. September 2001" },

  // ===== Zusätzliche Marker: Afrika, Amerika, Asien & mehr =====
  { lat: 31.32, lng: 45.64, icon: "💡", show: [-3000, -2000], title: "Uruk – Erfindung der Schrift (~3200 v. Chr.)",
    text: "In der sumerischen Metropole Uruk entsteht die Keilschrift – zuerst für Buchhaltung, dann für alles: Die Geschichte wird schriftlich.", wiki: "Uruk" },
  { lat: 27.33, lng: 68.14, icon: "🏛️", show: [-3000, -1500], title: "Indus-Kultur – Mohenjo-daro (~2600 v. Chr.)",
    text: "Planstädte mit Kanalisation und genormten Ziegeln – eine Hochkultur, deren Schrift bis heute nicht entziffert ist.", wiki: "Mohenjo-daro" },
  { lat: 51.18, lng: -1.83, icon: "🏛️", show: [-3000, -2000], title: "Stonehenge (~2500 v. Chr.)",
    text: "Der berühmteste Steinkreis der Welt – astronomisch ausgerichtet, Zweck bis heute rätselhaft: Europa hatte auch ohne Schrift komplexe Kulturen.", wiki: "Stonehenge" },
  { lat: 36.36, lng: 43.16, icon: "🔥", show: [-700, -500], title: "Fall Ninives (612 v. Chr.)",
    text: "Babylonier und Meder zerstören die assyrische Hauptstadt – das Ende der ersten Militär-Supermacht der Geschichte.", wiki: "Ninive" },
  { lat: 32.54, lng: 44.42, icon: "👑", show: [-500, -500], title: "Kyros nimmt Babylon (539 v. Chr.)",
    text: "Der Perserkönig erobert die größte Stadt der Welt fast kampflos und lässt die Juden aus dem Exil heimkehren – Toleranz als Herrschaftsprinzip.", wiki: "Kyros II." },
  { lat: 29.93, lng: 52.89, icon: "🏛️", show: [-500, -400], title: "Persepolis (ab ~518 v. Chr.)",
    text: "Prunkresidenz der Perserkönige – Völker aus aller Welt bringen auf den Reliefs Tribut. 330 v. Chr. brennt Alexander sie nieder.", wiki: "Persepolis" },
  { lat: 20.24, lng: 85.83, icon: "⛪", show: [-300, -200], title: "Ashoka und Kalinga (~261 v. Chr.)",
    text: "Nach dem blutigen Kalinga-Feldzug bereut Kaiser Ashoka öffentlich, wendet sich dem Buddhismus zu und regiert fortan nach dem Prinzip der Gewaltlosigkeit.", wiki: "Ashoka" },
  { lat: 41.08, lng: 14.25, icon: "⚔️", show: [-100, -100], title: "Spartacus-Aufstand (73–71 v. Chr.)",
    text: "Ein Gladiator aus Capua führt 100.000 entflohene Sklaven – Rom braucht acht Legionen; 6000 Gefangene enden gekreuzigt an der Via Appia.", wiki: "Spartacus" },
  { lat: 19.69, lng: -98.84, icon: "🏛️", show: [100, 500], title: "Teotihuacán – Blüte (~100–550)",
    text: "Mit ~150.000 Einwohnern eine der größten Städte der Welt – Sonnenpyramide, Planstadt. Die Azteken finden später nur Ruinen: „Ort, wo man zum Gott wird“.", wiki: "Teotihuacán" },
  { lat: 17.22, lng: -89.62, icon: "🏛️", show: [300, 900], title: "Maya – klassische Zeit (~250–900)",
    text: "Tikal, Palenque, Copán: Stadtstaaten mit Schrift, Null und präzisem Kalender – um 900 kollabiert das Tiefland, vermutlich durch Dürren und Kriege.", wiki: "Maya" },
  { lat: 25.61, lng: 85.14, icon: "💡", show: [400, 500], title: "Gupta-Blüte – die Null (~450)",
    text: "In Pataliputra blüht Indiens goldenes Zeitalter: Dezimalsystem mit Null, Aryabhata berechnet Pi – kaum eine Erfindung war folgenreicher.", wiki: "Gupta-Reich" },
  { lat: 42.52, lng: 72.23, icon: "⚔️", show: [700, 800], title: "Schlacht am Talas (751)",
    text: "Araber schlagen China – Zentralasien wird islamisch, und gefangene Papiermacher bringen die chinesische Erfindung nach Westen.", wiki: "Schlacht am Talas" },
  { lat: 37.88, lng: -4.78, icon: "💡", show: [800, 1000], title: "Córdoba – Blüte von al-Andalus (ab 756)",
    text: "Hunderttausende Einwohner, Straßenbeleuchtung, riesige Bibliotheken, die Mezquita – die glänzendste Stadt Westeuropas, Ort dreier Religionen.", wiki: "Kalifat von Córdoba" },
  { lat: 38.66, lng: -90.06, icon: "🏛️", show: [1000, 1300], title: "Cahokia (~1050–1350)",
    text: "Die größte Stadt des vorkolumbischen Nordamerika: Erdpyramiden am Mississippi, ~20.000 Einwohner – mehr als das damalige London.", wiki: "Cahokia" },
  { lat: 13.41, lng: 103.86, icon: "🏛️", show: [1100, 1400], title: "Angkor Wat (12. Jh.)",
    text: "Das größte religiöse Bauwerk der Erde im mächtigsten Reich Südostasiens – Wasserbau-Ingenieurskunst ernährt eine Millionenstadt.", wiki: "Angkor Wat" },
  { lat: -20.27, lng: 30.93, icon: "🏛️", show: [1200, 1400], title: "Great Zimbabwe (~1100–1450)",
    text: "Steinerne Königsstadt im südlichen Afrika, reich durch Gold- und Elfenbeinhandel bis China – Namensgeber des heutigen Simbabwe.", wiki: "Great Zimbabwe" },
  { lat: 16.77, lng: -3.01, icon: "💡", show: [1300, 1500], title: "Timbuktu – Gold und Bücher (14.–16. Jh.)",
    text: "Handelsdrehscheibe des Transsahara-Handels und Universitätsstadt: Zehntausende Handschriften – Jura, Astronomie, Medizin – widerlegen den Mythos vom „geschichtslosen“ Afrika.", wiki: "Timbuktu" },
  { lat: 32.06, lng: 118.78, icon: "🚢", show: [1400, 1400], title: "Zheng Hes Schatzflotten (1405–1433)",
    text: "Von Nanjing aus segeln Riesenflotten bis Ostafrika – dann bricht China ab und wendet sich nach innen: eine der großen „Was-wäre-wenn“-Fragen der Geschichte.", wiki: "Zheng He" },
  { lat: -19.59, lng: -65.75, icon: "🔥", show: [1600, 1700], title: "Potosí – der Silberberg (ab 1545)",
    text: "Der Cerro Rico finanziert Spaniens Weltmacht – gefördert von indigenen Zwangsarbeitern unter mörderischen Bedingungen; das Silber fließt bis nach China.", wiki: "Potosí" },
  { lat: 41.96, lng: -70.66, icon: "🚢", show: [1650, 1650], title: "Mayflower & Neuengland (1620)",
    text: "Die Pilgerväter landen bei Plymouth – religiöse Dissidenten gründen Kolonien, deren Selbstverwaltungstradition die USA prägen wird.", wiki: "Mayflower" },
  { lat: 27.17, lng: 78.04, icon: "🏛️", show: [1650, 1700], title: "Taj Mahal (1632–1648)",
    text: "Shah Jahans Grabmal für seine Frau Mumtaz Mahal – Höhepunkt der Mogul-Architektur, erbaut auf dem Zenit des reichsten Reichs der Erde.", wiki: "Taj Mahal" },
  { lat: -33.92, lng: 18.42, icon: "🚢", show: [1700, 1700], title: "Kapstadt gegründet (1652)",
    text: "Die VOC baut eine Versorgungsstation am Kap – Keimzelle der späteren Kapkolonie und des konfliktreichen Südafrika.", wiki: "Kapstadt" },
  { lat: 35.68, lng: 139.75, icon: "👑", show: [1700, 1783], title: "Edo – Japans Abschottung (Sakoku)",
    text: "Unter den Tokugawa wächst Edo (Tokio) zur Millionenstadt – 250 Jahre Frieden hinter geschlossenen Grenzen, nur ein holländischer Handelsposten bleibt.", wiki: "Sakoku" },
  { lat: 14.67, lng: -17.40, icon: "🔥", show: [1700, 1815], title: "Gorée – transatlantischer Sklavenhandel",
    text: "Symbol des Menschenhandels: ~12 Millionen Afrikaner werden über den Atlantik verschleppt – die Plantagenökonomie Amerikas baut auf ihnen auf.", wiki: "Atlantischer Sklavenhandel" },
  { lat: -33.86, lng: 151.21, icon: "🚢", show: [1783, 1800], title: "Erste Flotte in Australien (1788)",
    text: "Großbritannien gründet die Sträflingskolonie Sydney – für die Aborigines, seit 60.000 Jahren im Land, beginnt die Enteignung.", wiki: "First Fleet" },
  { lat: 48.21, lng: 16.37, icon: "👑", show: [1815, 1815], title: "Wiener Kongress (1814/15)",
    text: "„Der Kongress tanzt“ – Metternich und die Sieger ordnen Europa neu: Restauration und Mächtegleichgewicht halten (fast) 100 Jahre den Großkrieg fern.", wiki: "Wiener Kongress" },
  { lat: 30.70, lng: 32.34, icon: "💡", show: [1880, 1880], title: "Suezkanal eröffnet (1869)",
    text: "Der Weg nach Indien verkürzt sich um Wochen – strategische Lebensader des Empire; 1882 besetzt Großbritannien gleich ganz Ägypten.", wiki: "Sueskanal" },
  { lat: 35.68, lng: 139.75, icon: "👑", show: [1880, 1900], title: "Meiji-Restauration (1868)",
    text: "Japan modernisiert sich in einer Generation radikal selbst – Verfassung, Industrie, Wehrpflicht: das Lehrbuchbeispiel nachholender Modernisierung.", wiki: "Meiji-Restauration" },
  { lat: 14.17, lng: 38.90, icon: "⚔️", show: [1900, 1900], title: "Schlacht von Adwa (1896)",
    text: "Kaiser Menelik II. schlägt die italienische Kolonialarmee – Äthiopien bleibt als einziger afrikanischer Staat dauerhaft unabhängig.", wiki: "Schlacht von Adua" },
  { lat: -20.50, lng: 17.24, icon: "🔥", show: [1914, 1914], title: "Völkermord an Herero und Nama (1904–1908)",
    text: "Deutsche Truppen treiben die Aufständischen in die Omaheke-Wüste – der erste Genozid des 20. Jahrhunderts.", wiki: "Völkermord an den Herero und Nama" },
  { lat: 9.08, lng: -79.68, icon: "💡", show: [1920, 1920], title: "Panamakanal eröffnet (1914)",
    text: "Die USA verbinden die Ozeane – Ingenieurstriumph und Symbol der neuen Weltmacht, die sich zuvor gleich die Provinz Panama „beschafft“ hatte.", wiki: "Panamakanal" },
  { lat: 20.89, lng: 72.81, icon: "💡", show: [1930, 1938], title: "Gandhis Salzmarsch (1930)",
    text: "380 km zu Fuß ans Meer, um verbotenes Salz zu gewinnen – gewaltfreier Massenprotest, der das Empire moralisch in die Defensive zwingt.", wiki: "Salzmarsch" },
  { lat: 43.32, lng: -2.68, icon: "🔥", show: [1938, 1938], title: "Guernica (1937)",
    text: "Die deutsche Legion Condor bombardiert die baskische Stadt – Generalprobe des Luftkriegs; Picassos Gemälde macht das Grauen unsterblich.", wiki: "Gernika" },
  { lat: 44.47, lng: 34.14, icon: "👑", show: [1945, 1945], title: "Konferenz von Jalta (Februar 1945)",
    text: "Roosevelt, Churchill und Stalin teilen die Nachkriegswelt in Einflusszonen – die Landkarte des Kalten Kriegs entsteht am Schwarzen Meer.", wiki: "Konferenz von Jalta" },
  { lat: 49.45, lng: 11.05, icon: "💡", show: [1945, 1945], title: "Nürnberger Prozesse (1945/46)",
    text: "Erstmals stehen Führer eines Staates vor einem internationalen Gericht – Geburtsstunde des Völkerstrafrechts.", wiki: "Nürnberger Prozesse" },
  { lat: 31.78, lng: 35.22, icon: "👑", show: [1960, 1960], title: "Staatsgründung Israels (1948)",
    text: "Aus Zionismus und Holocaust-Schock entsteht der jüdische Staat; im ersten Krieg fliehen ~700.000 Palästinenser („Nakba“) – der Konflikt prägt die Region bis heute.", wiki: "Israelische Unabhängigkeitserklärung" },
  { lat: 5.56, lng: -0.20, icon: "👑", show: [1960, 1960], title: "Ghana – Dekolonisierung Afrikas (1957)",
    text: "Als erste Kolonie Schwarzafrikas wird Ghana unter Nkrumah unabhängig – 1960 folgen allein 17 Staaten: das „Afrikanische Jahr“.", wiki: "Kwame Nkrumah" },
  { lat: 28.50, lng: -80.65, icon: "💡", show: [1960, 1994], title: "Wettlauf ins All – Mondlandung (1969)",
    text: "Von Cape Canaveral zur Mondlandung: Apollo 11 gewinnt den Prestigekampf der Systeme – „ein riesiger Sprung für die Menschheit“.", wiki: "Apollo 11" },
  { lat: 50.09, lng: 14.42, icon: "🔥", show: [1960, 1994], title: "Prager Frühling (1968)",
    text: "„Sozialismus mit menschlichem Antlitz“ – Warschauer-Pakt-Panzer walzen die Reform nieder; die Illusion eines reformierbaren Ostblocks stirbt.", wiki: "Prager Frühling" },
  { lat: 51.39, lng: 30.10, icon: "🔥", show: [1994, 1994], title: "Tschernobyl (1986)",
    text: "Der GAU verstrahlt halb Europa – und Gorbatschows Glasnost bekommt ihren Ernstfall: Die Vertuschung beschleunigt den Vertrauensverlust ins System.", wiki: "Nuklearkatastrophe von Tschernobyl" },
  { lat: 44.10, lng: 19.30, icon: "🔥", show: [1994, 2000], title: "Srebrenica (1995)",
    text: "Serbische Truppen ermorden ~8.000 bosniakische Männer und Jungen in einer UN-„Schutzzone“ – der schlimmste Völkermord in Europa seit 1945.", wiki: "Massaker von Srebrenica" },
  { lat: 22.32, lng: 114.17, icon: "👑", show: [2000, 2000], title: "Übergabe Hongkongs (1997)",
    text: "Nach 156 Jahren endet die britische Kronkolonie – „ein Land, zwei Systeme“ verspricht 50 Jahre Autonomie; symbolisches Ende des Empire.", wiki: "Übergabe Hongkongs" },
  { lat: 50.85, lng: 5.69, icon: "👑", show: [2000, 2010], title: "Maastricht – die EU entsteht (1992)",
    text: "Aus der Wirtschaftsgemeinschaft wird die Europäische Union mit gemeinsamer Währung – das ambitionierteste Friedensprojekt der Geschichte.", wiki: "Vertrag von Maastricht" },
  { lat: 33.34, lng: 44.40, icon: "⚔️", show: [2010, 2010], title: "Irakkrieg (2003)",
    text: "Die USA stürzen Saddam Hussein ohne UN-Mandat – die behaupteten Massenvernichtungswaffen existieren nicht; die Region destabilisiert sich auf Jahrzehnte.", wiki: "Irakkrieg" }
];
