// Automatische Inline-Verlinkung: wandelt bekannte <b>Begriffe</b> in Fließtexten
// (Epochen-Panel, Länder-Berichte) in Links zur deutschen Wikipedia um.
// Schlüssel müssen exakt dem Text innerhalb von <b>...</b> entsprechen
// (ein optionaler, abschließender Doppelpunkt wird automatisch abgetrennt).

const WIKI_TERMS = {
  // Personen – Herrscher & Politiker
  "Ludwig XIV.": "Ludwig XIV.", "Ludwig XVI.": "Ludwig XVI.",
  "Elisabeth I.": "Elisabeth I.", "Heinrich VIII.": "Heinrich VIII. (England)",
  "Friedrich der Große": "Friedrich II. (Preußen)", "Maria Theresia": "Maria Theresia",
  "Katharina die Große": "Katharina II.", "Peter der Große": "Peter der Große",
  "Karl XII.": "Karl XII. (Schweden)", "Gustav II. Adolf": "Gustav II. Adolf",
  "Napoleon Bonaparte": "Napoleon Bonaparte", "Bismarck": "Otto von Bismarck",
  "Wilhelm II.": "Wilhelm II. (Deutsches Reich)", "Cavour": "Camillo Benso von Cavour",
  "Garibaldi": "Giuseppe Garibaldi", "Mussolini": "Benito Mussolini",
  "Franco": "Francisco Franco", "Hitler": "Adolf Hitler", "Stalin": "Josef Stalin",
  "Gandhi": "Mohandas Karamchand Gandhi", "Ho Chi Minh": "Hồ Chí Minh",
  "Tito": "Josip Broz Tito", "Deng Xiaoping": "Deng Xiaoping",
  "Simón Bolívar": "Simón Bolívar", "San Martín": "José de San Martín",
  "Cortés": "Hernán Cortés", "Pizarro": "Francisco Pizarro",
  "Justinian": "Justinian I.", "Konstantin": "Konstantin der Große",
  "Chlodwig": "Chlodwig I.", "Karl der Große": "Karl der Große",
  "Dschingis Khan": "Dschingis Khan", "Mehmed II.": "Mehmed II.",
  "Süleyman dem Prächtigen": "Süleyman I.", "Akbar der Große": "Akbar (Großmogul)",
  "Aurangzeb": "Aurangzeb", "Abbas dem Großen": "Abbas I. (Schah)",
  "Wu Zetian": "Wu Zetian", "Zheng He": "Zheng He", "Sejong der Große": "Sejong",
  "Ashoka": "Ashoka", "Trajan": "Trajan", "Augustus": "Augustus",
  "Marc Aurel": "Mark Aurel", "Caesar": "Gaius Iulius Caesar", "Attila": "Attila",
  "Saladin": "Saladin", "Wladimir": "Wladimir I.",
  "Mansa Musa": "Mansa Musa", "Nizam al-Mulk": "Nizam al-Mulk",
  "al-Chwarizmi": "Al-Chwarizmi",

  // Personen – Denker, Wissenschaftler, Künstler
  "Averroes": "Averroes", "Maimonides": "Maimonides",
  "Thomas von Aquin": "Thomas von Aquin", "Franziskus von Assisi": "Franziskus von Assisi",
  "Papst Gregor der Große": "Gregor I. (Papst)", "Aristoteles": "Aristoteles",
  "Herodot": "Herodot", "Hippokrates": "Hippokrates",
  "Augustinus": "Augustinus von Hippo", "Meister Eckhart": "Meister Eckhart",
  "Wilhelm von Ockham": "Wilhelm von Ockham", "Marsilius von Padua": "Marsilius von Padua",
  "Petrarca": "Francesco Petrarca", "Dante": "Dante Alighieri",
  "Leonardo da Vinci": "Leonardo da Vinci", "Machiavelli": "Niccolò Machiavelli",
  "Kopernikus": "Nikolaus Kopernikus", "Galilei": "Galileo Galilei",
  "Kepler": "Johannes Kepler", "Newton": "Isaac Newton",
  "Descartes": "René Descartes", "Spinoza": "Baruch de Spinoza",
  "Francis Bacon": "Francis Bacon", "Hugo Grotius": "Hugo Grotius",
  "Jean Bodin": "Jean Bodin", "Thomas Hobbes": "Thomas Hobbes",
  "John Locke": "John Locke", "Voltaire": "Voltaire",
  "Montesquieu": "Montesquieu", "Rousseau": "Jean-Jacques Rousseau",
  "Adam Smith": "Adam Smith", "Beccaria": "Cesare Beccaria",
  "Olympe de Gouges": "Olympe de Gouges", "Richelieu": "Armand-Jean du Plessis de Richelieu",
  "Seneca": "Seneca", "Epiktet": "Epiktet", "Darwin": "Charles Darwin",
  "Freud": "Sigmund Freud", "Nietzsche": "Friedrich Nietzsche",
  "Buddha": "Siddhartha Gautama", "Konfuzius": "Konfuzius",

  // Kriege, Schlachten, Verträge
  "Erster Weltkrieg": "Erster Weltkrieg",
  "Zweiter Weltkrieg": "Zweiter Weltkrieg", "Zweite Weltkrieg": "Zweiter Weltkrieg",
  "Dreißigjähriger Krieg": "Dreißigjähriger Krieg", "Dreißigjährige Krieg": "Dreißigjähriger Krieg",
  "Hundertjähriger Krieg": "Hundertjähriger Krieg",
  "Siebenjähriger Krieg": "Siebenjähriger Krieg",
  "Großer Nordischer Krieg": "Großer Nordischer Krieg",
  "Amerikanischer Bürgerkrieg": "Sezessionskrieg",
  "Amerikanischer Unabhängigkeitskrieg": "Amerikanischer Unabhängigkeitskrieg",
  "Krimkrieg": "Krimkrieg", "Koreakrieg": "Koreakrieg", "Vietnamkrieg": "Vietnamkrieg",
  "Russisch-Japanischer Krieg": "Russisch-Japanischer Krieg",
  "Peloponnesischer Krieg": "Peloponnesischer Krieg", "Peloponnesische Krieg": "Peloponnesischer Krieg",
  "Punische Kriege": "Punische Kriege", "Punischen Kriegen": "Punische Kriege",
  "Perserkriege": "Perserkriege", "Jüdische Kriege": "Jüdischer Krieg",
  "Völkerwanderung": "Völkerwanderung", "Arabische Expansion": "Islamische Expansion",
  "Spanischer Erbfolgekrieg": "Spanischer Erbfolgekrieg",
  "Großer Sprung nach vorn": "Großer Sprung nach vorn", "Kulturrevolution": "Kulturrevolution",
  "Taiping-Aufstand": "Taiping-Aufstand", "Opiumkriegen": "Erster Opiumkrieg",
  "Völkermord an den Armeniern": "Völkermord an den Armeniern",
  "Holocaust": "Holocaust", "Holodomor": "Holodomor",
  "Srebrenica": "Massaker von Srebrenica", "Guernica": "Gernika",
  "Spanische Bürgerkrieg": "Spanischer Bürgerkrieg", "Kuba-Krise": "Kubakrise",
  "Tet-Offensive": "Tet-Offensive", "Dien Bien Phu": "Schlacht von Điện Biên Phủ",
  "Weltwirtschaftskrise": "Weltwirtschaftskrise",
  "Bill of Rights 1689": "Bill of Rights (England)", "Magna Carta": "Magna Carta",
  "Westfälische Friede": "Westfälischer Friede", "Westfälische Friede 1648": "Westfälischer Friede",
  "Augsburger Religionsfriede": "Augsburger Reichs- und Religionsfrieden",
  "Edikt von Nantes": "Edikt von Nantes",
  "Erklärung der Menschen- und Bürgerrechte": "Erklärung der Menschen- und Bürgerrechte",
  "Verfassung von 1787": "Verfassung der Vereinigten Staaten", "Code Civil": "Code civil",
  "Vertrag von Verdun 843": "Vertrag von Verdun", "Investiturstreit": "Investiturstreit",
  "Bartholomäusnacht": "Bartholomäusnacht", "Glorious Revolution 1688": "Glorious Revolution",
  "Erster Kreuzzug": "Erster Kreuzzug",
  "Fall Konstantinopels 1453": "Eroberung von Konstantinopel (1453)",
  "Fall Ninives": "Ninive", "Schwarzer Tod": "Schwarzer Tod",
  "Manzikert": "Schlacht bei Manzikert", "Poltawa": "Schlacht bei Poltawa",
  "Varusschlacht": "Varusschlacht", "Waterloo 1815": "Schlacht bei Waterloo",
  "Belagerung Wiens 1529": "Erste Wiener Türkenbelagerung",
  "Wien 1683": "Zweite Wiener Türkenbelagerung",
  "zweiten Wiener Belagerung 1683": "Zweite Wiener Türkenbelagerung",
  "Ain Dschalut 1260": "Schlacht bei ʿAin Dschālūt",
  "Adwa": "Schlacht von Adua", "Schlacht von Kadesch": "Schlacht bei Kadesch",

  // Orte
  "Angkor Wat": "Angkor Wat", "Tenochtitlán": "Tenochtitlán", "Timbuktu": "Timbuktu",
  "Aksum": "Aksumitisches Reich", "Isfahan": "Isfahan", "Córdoba": "Córdoba",
  "Bagdad": "Bagdad", "Haus der Weisheit": "Haus der Weisheit",
  "Afrika": "Geschichte Afrikas", "Assyrien": "Assyrien", "Byzanz": "Byzantinisches Reich",
  "China": "Geschichte Chinas", "Deutschland": "Deutschland", "England": "Königreich England",
  "Griechenland": "Griechenland", "Großbritannien": "Vereinigtes Königreich",
  "Haiti": "Haiti", "Heiliges Römisches Reich": "Heiliges Römisches Reich",
  "Indien": "Indien", "Italien": "Italien", "Japan": "Japan",
  "Judäa": "Judäa (Provinz)", "Kalifat": "Kalifat", "Kiewer Rus": "Kiewer Rus",
  "Niederlande": "Niederlande", "Osmanisches Reich": "Osmanisches Reich",
  "Persien": "Persien", "Polen-Litauen": "Polen-Litauen", "Portugal": "Portugal",
  "Preußen": "Preußen", "Rom": "Rom", "Russland": "Russland", "Schweden": "Schweden",
  "Skandinavien": "Skandinavien", "Sowjetunion": "Sowjetunion", "Spanien": "Spanien",
  "Südafrika": "Südafrika", "USA": "Vereinigte Staaten", "Ägypten": "Ägypten",
  "Ungarn": "Ungarn", "Kaschmir": "Kaschmir-Konflikt",

  // Konzepte, Bewegungen, Epochen
  "Merkantilismus": "Merkantilismus", "Reformation": "Reformation",
  "Renaissance": "Renaissance", "Humanismus": "Humanismus", "Aufklärung": "Aufklärung",
  "Romantik": "Romantik (Epoche)", "Nationalismus": "Nationalismus",
  "Liberalismus": "Liberalismus", "Konservatismus": "Konservatismus",
  "Sozialismus": "Sozialismus", "Industrielle Revolution": "Industrielle Revolution",
  "zweite industrielle Revolution": "Zweite industrielle Revolution",
  "Industrialisierung": "Industrialisierung", "Sozialdarwinismus": "Sozialdarwinismus",
  "Existenzialismus": "Existentialismus", "Feminismus": "Feminismus",
  "Frauenbewegung": "Frauenbewegung",
  "Bürgerrechtsbewegung": "US-amerikanische Bürgerrechtsbewegung",
  "Dekolonisierung": "Dekolonisierung", "Globalisierung": "Globalisierung",
  "Monotheismus": "Monotheismus", "Scholastik": "Scholastik",
  "Neuplatonismus": "Neuplatonismus", "Stoa": "Stoa (Philosophie)",
  "Epikureismus": "Epikureismus", "Legalismus": "Legalismus (China)",
  "Konfuzianismus": "Konfuzianismus", "Christentum": "Christentum", "Islam": "Islam",
  "Hellenismus": "Hellenismus", "Polis": "Polis", "Pharao": "Pharao",
  "Maat": "Maat (Mythologie)", "Achsenzeit": "Achsenzeit", "Mönchtum": "Mönchtum",
  "Alphabet": "Alphabet", "Seidenstraße": "Seidenstraße", "Hangul": "Hangul",
  "Dezimalsystem mit der Null": "Indische Ziffern",
  "Pax Romana": "Pax Romana", "Pax Mongolica": "Pax Mongolica", "Pax Britannica": "Pax Britannica",
  "Terrorherrschaft": "Terreur", "Girondisten": "Girondisten", "Feuillants": "Feuillants",
  "Sansculotten": "Sansculotten", "Risorgimento": "Risorgimento",
  "Dreyfus-Affäre": "Dreyfus-Affäre", "Pariser Kommune": "Pariser Kommune",
  "Zweites Kaiserreich": "Zweites Kaiserreich", "Dritte Republik": "Dritte Französische Republik",
  "British Raj": "Britisch-Indien", "East India Company": "Britische Ostindien-Kompanie",
  "VOC": "Niederländische Ostindien-Kompanie", "Meiji-Restauration": "Meiji-Restauration",
  "Tokugawa-Shogune": "Tokugawa-Shōgunat", "Joseon-Dynastie": "Joseon-Dynastie",
  "Tang-Dynastie": "Tang-Dynastie", "Gupta-Reich": "Gupta-Reich", "Gupta": "Gupta-Reich",
  "Maurya-Reich": "Maurya-Reich", "Mongolenreich": "Mongolisches Reich",
  "Songhai": "Songhaireich", "Mali": "Malireich",
  "Wikinger": "Wikinger", "Wikingerzeit": "Wikingerzeit", "Sarazenen": "Sarazenen",
  "Reconquista": "Reconquista", "Achämenidenreich": "Achämenidenreich",
  "Sassaniden": "Sassanidenreich", "Parther": "Partherreich",
  "Kreuzfahrer": "Kreuzfahrerstaaten", "Liberum Veto": "Liberum Veto",
  "Kampf der Kulturen": "Kampf der Kulturen", "Ende der Geschichte": "Das Ende der Geschichte",
  "Internet": "Internet", "Umweltbewegung": "Umweltbewegung",
  "Diaspora": "Jüdische Diaspora", "Transición": "Transición",
  "faschistische Diktatur": "Italienischer Faschismus",
  "Sklavenhandel": "Atlantischer Sklavenhandel",
  "Haitianische Revolution": "Haitianische Revolution",

  // Vorgeschichte
  "Lascaux": "Höhle von Lascaux", "Venus von Willendorf": "Venus von Willendorf",
  "Megalithkultur": "Megalithkultur", "Göbekli Tepe": "Göbekli Tepe", "Jericho": "Jericho",

  // Architekten, Künstler, Komponisten, Schriftsteller, Philosophen (Kunst & Architektur je Epoche)
  "Imhotep": "Imhotep", "Homer": "Homer", "Phidias": "Phidias",
  "Sophokles": "Sophokles", "Euripides": "Euripides",
  "Vergil": "Vergil", "Ovid": "Ovid", "Hieronymus": "Hieronymus (Kirchenvater)",
  "Anthemios von Tralleis": "Anthemios von Tralleis", "Isidor von Milet": "Isidor von Milet",
  "Beda Venerabilis": "Beda Venerabilis", "Alkuin von York": "Alkuin",
  "al-Kindi": "Al-Kindi", "Abt Suger": "Suger von Saint-Denis",
  "Hildegard von Bingen": "Hildegard von Bingen", "Anselm von Canterbury": "Anselm von Canterbury",
  "Omar Chayyam": "Omar Chayyām", "Rumi": "Rumi", "Marco Polo": "Marco Polo",
  "Giotto di Bondone": "Giotto di Bondone", "Brunelleschi": "Filippo Brunelleschi",
  "Michelangelo": "Michelangelo", "Raffael": "Raffael",
  "Erasmus von Rotterdam": "Erasmus von Rotterdam", "Albrecht Dürer": "Albrecht Dürer",
  "Caravaggio": "Caravaggio", "El Greco": "El Greco",
  "William Shakespeare": "William Shakespeare", "Miguel de Cervantes": "Miguel de Cervantes",
  "Rembrandt": "Rembrandt van Rijn", "Versailles": "Schloss Versailles",
  "André Le Nôtre": "André Le Nôtre", "Jean-Baptiste Lully": "Jean-Baptiste Lully",
  "Christopher Wren": "Christopher Wren", "Hagia Sophia": "Hagia Sophia",
  "Johann Sebastian Bach": "Johann Sebastian Bach", "Wolfgang Amadeus Mozart": "Wolfgang Amadeus Mozart",
  "Immanuel Kant": "Immanuel Kant", "Denis Diderot": "Denis Diderot",
  "Antonio Canova": "Antonio Canova", "Jacques-Louis David": "Jacques-Louis David",
  "Francisco de Goya": "Francisco de Goya", "Johann Wolfgang von Goethe": "Johann Wolfgang von Goethe",
  "Ludwig van Beethoven": "Ludwig van Beethoven", "Caspar David Friedrich": "Caspar David Friedrich",
  "Eugène Delacroix": "Eugène Delacroix", "Charles Dickens": "Charles Dickens",
  "Karl Marx": "Karl Marx", "Richard Wagner": "Richard Wagner",
  "Claude Monet": "Claude Monet", "Vincent van Gogh": "Vincent van Gogh",
  "Antoni Gaudí": "Antoni Gaudí", "Gustav Klimt": "Gustav Klimt",
  "Walter Gropius": "Walter Gropius", "Pablo Picasso": "Pablo Picasso",
  "Salvador Dalí": "Salvador Dalí", "Ernest Hemingway": "Ernest Hemingway",
  "Martin Heidegger": "Martin Heidegger", "Andy Warhol": "Andy Warhol",
  "Jackson Pollock": "Jackson Pollock", "Ludwig Mies van der Rohe": "Ludwig Mies van der Rohe",
  "Jean-Paul Sartre": "Jean-Paul Sartre", "Albert Camus": "Albert Camus",
  "The Beatles": "The Beatles", "Frank Gehry": "Frank Gehry",
  "Zaha Hadid": "Zaha Hadid", "Banksy": "Banksy", "Ai Weiwei": "Ai Weiwei",
  "Euklid": "Euklid", "Archimedes": "Archimedes", "Eratosthenes": "Eratosthenes",
  "Plotin": "Plotin", "Ibn Chaldun": "Ibn Chaldūn",

  // Baustile & Kunstepochen
  "karolingische Renaissance": "Karolingische Renaissance", "romanische Baustil": "Romanik",
  "Gotik": "Gotik", "Hochrenaissance": "Renaissance", "Barock": "Barock",
  "Rokoko": "Rokoko", "Klassizismus": "Klassizismus", "Realismus": "Realismus (Kunst)",
  "Impressionismus": "Impressionismus", "Jugendstil": "Jugendstil",
  "Dada": "Dadaismus", "Bauhaus": "Bauhaus", "Pop-Art": "Pop-Art", "Streetart": "Street Art"
};

function linkify(html, lang = 'de') {
  if (lang === 'en') {
    // Englische Texte: fette Begriffe auf en.wikipedia verlinken
    // (Special:Search leitet bei eindeutigen Treffern direkt zum Artikel weiter)
    return html.replace(/<b>([^<]+?)(:?)<\/b>/g, (match, name, colon) => {
      const href = 'https://en.wikipedia.org/wiki/Special:Search?search=' + encodeURIComponent(name);
      return `<b><a class="inline-wiki" href="${href}" target="_blank" rel="noopener">${name}</a>${colon}</b>`;
    });
  }
  return html.replace(/<b>([^<]+?)(:?)<\/b>/g, (match, name, colon) => {
    const title = WIKI_TERMS[name];
    if (!title) return match;
    const href = 'https://de.wikipedia.org/wiki/' + encodeURIComponent(title.replace(/ /g, '_'));
    return `<b><a class="inline-wiki" href="${href}" target="_blank" rel="noopener">${name}</a>${colon}</b>`;
  });
}
